#!/usr/bin/env python3
"""
Minimal DB maintainer script for scheduled reminder.
Performs:
- Generate a limited directory tree snapshot of the workspace (depth 8) and write to important/openclaw-tree.txt
- Create backups of docs.db and tree.db if they exist, stored in db/backups with timestamp
- Remove backups older than 3 days
- Update db/maintainer_state.json with timestamps
- Log actions to logs/db-maintainer/YYYY-MM-DD.log
"""

import json
import os
import shutil
from datetime import datetime, timedelta
from pathlib import Path

# Paths
WORKSPACE = Path(__file__).resolve().parent.parent
DB_DIR = WORKSPACE / "db"
BACKUP_DIR = DB_DIR / "backups"
LOG_DIR = WORKSPACE / "logs" / "db-maintainer"
IMPORTANT_DIR = WORKSPACE / "important"
STATE_FILE = DB_DIR / "maintainer_state.json"

# Ensure directories exist
for d in [BACKUP_DIR, LOG_DIR, IMPORTANT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# Simple logger
class Logger:
    def __init__(self):
        today = datetime.now().strftime('%Y-%m-%d')
        self.log_path = LOG_DIR / f"{today}.log"
    def _log(self, level, msg):
        ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        line = f"[{ts}] [{level}] {msg}"
        print(line)
        with open(self.log_path, 'a') as f:
            f.write(line + '\n')
    def info(self, msg): self._log('INFO', msg)
    def warn(self, msg): self._log('WARN', msg)
    def error(self, msg): self._log('ERROR', msg)

logger = Logger()

def generate_tree(max_depth=8):
    """Generate a simple tree representation up to max_depth levels."""
    lines = []
    def walk(path, prefix="", depth=0):
        if depth > max_depth:
            return
        try:
            entries = sorted([e for e in os.listdir(path) if not e.startswith('.')])
        except Exception as e:
            logger.error(f"Failed to list {path}: {e}")
            return
        for i, name in enumerate(entries):
            full = Path(path) / name
            connector = "├─ " if i < len(entries) - 1 else "└─ "
            lines.append(f"{prefix}{connector}{name}")
            if full.is_dir():
                new_prefix = prefix + ("│   " if i < len(entries) - 1 else "    ")
                walk(full, new_prefix, depth + 1)
    walk(str(WORKSPACE))
    return "\n".join(lines)

def write_tree_file():
    tree_content = generate_tree()
    if not tree_content:
        logger.warn("Tree content is empty, not writing file.")
        return False
    header = f"# OpenClaw Workspace Tree\n# Generated: {datetime.now().isoformat()}\n# Command: generated by db_maintainer_run\n\n"
    out_path = IMPORTANT_DIR / "openclaw-tree.txt"
    try:
        with open(out_path, 'w') as f:
            f.write(header)
            f.write(tree_content)
        logger.info(f"Wrote tree snapshot to {out_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to write tree file: {e}")
        return False

def backup_db(db_name):
    src = DB_DIR / db_name
    if not src.exists():
        logger.warn(f"{db_name} not found, skipping backup.")
        return False
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M')
    backup_name = f"{timestamp}_{db_name}.bak"
    dest = BACKUP_DIR / backup_name
    try:
        shutil.copy2(src, dest)
        logger.info(f"Backup created: {dest.name}")
        return True
    except Exception as e:
        logger.error(f"Failed to backup {db_name}: {e}")
        return False

def cleanup_backups(retention_days=3):
    cutoff = datetime.now() - timedelta(days=retention_days)
    removed = 0
    for file in BACKUP_DIR.iterdir():
        if not file.is_file():
            continue
        # Expect format YYYY-MM-DD_HH-MM_<db>.bak
        parts = file.name.split('_')
        if len(parts) < 3:
            continue
        date_part = parts[0]
        time_part = parts[1]
        try:
            file_dt = datetime.strptime(f"{date_part}_{time_part}", "%Y-%m-%d_%H-%M")
            if file_dt < cutoff:
                file.unlink()
                removed += 1
                logger.info(f"Old backup removed: {file.name}")
        except Exception:
            # Skip unparsable names
            continue
    if removed == 0:
        logger.info("No old backups to remove.")

def load_state():
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE, 'r') as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Failed to load state file: {e}")
    # Default state structure
    return {"last_check": None, "last_backup": None, "last_tree_update": None, "file_hashes": {}}

def save_state(state):
    try:
        with open(STATE_FILE, 'w') as f:
            json.dump(state, f, indent=2)
        logger.info("State file updated.")
    except Exception as e:
        logger.error(f"Failed to write state file: {e}")

def main():
    logger.info("=== DB Maintainer run start ===")
    state = load_state()
    # Tree snapshot
    if write_tree_file():
        state['last_tree_update'] = datetime.now().isoformat()
    # Backups
    backed_up = False
    for db in ["docs.db", "tree.db"]:
        if backup_db(db):
            backed_up = True
    if backed_up:
        state['last_backup'] = datetime.now().isoformat()
    # Cleanup old backups
    cleanup_backups()
    # Update last_check timestamp (simple marker that script ran)
    state['last_check'] = datetime.now().isoformat()
    save_state(state)
    logger.info("=== DB Maintainer run end ===")

if __name__ == "__main__":
    main()
