#!/usr/bin/env python3
"""Simplified DB Maintainer script for heartbeat reminder.
Runs the tree command, updates the openclaw-tree.txt file, executes the
update_docs_db and tree_indexer_v2 scripts, creates backups of the
SQLite databases, and cleans up old backups (retention 3 days)."""

import subprocess
import sys
from pathlib import Path
from datetime import datetime, timedelta
from shutil import copy2

# Define workspace paths
WORKSPACE = Path("/workspace")
DB_DIR = WORKSPACE / "db"
BACKUP_DIR = DB_DIR / "backups"
LOG_DIR = WORKSPACE / "logs" / "db-maintainer"
IMPORTANT_DIR = WORKSPACE / "important"

# Ensure directories exist
for p in (DB_DIR, BACKUP_DIR, LOG_DIR, IMPORTANT_DIR):
    p.mkdir(parents=True, exist_ok=True)

# Simple logger to stdout
def log(level, msg):
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    print(f"[{ts}] [{level}] {msg}")

def run_tree():
    try:
        result = subprocess.run(['tree', '-a', '-L', '8', str(WORKSPACE)],
                                 capture_output=True, text=True, timeout=60)
        if result.returncode != 0:
            log('ERROR', f"tree command failed: {result.stderr.strip()}")
            return None
        return result.stdout
    except Exception as e:
        log('ERROR', f"tree command exception: {e}")
        return None

def write_tree_file(output):
    if not output:
        return
    tree_file = IMPORTANT_DIR / "openclaw-tree.txt"
    header = f"# OpenClaw Workspace Tree\n# Generated: {datetime.now().isoformat()}\n# Command: tree -a -L 8 {WORKSPACE}\n# Auto-generated by db-maintainer\n\n"
    try:
        with open(tree_file, 'w') as f:
            f.write(header)
            f.write(output)
        log('INFO', f"Updated tree file at {tree_file}")
    except Exception as e:
        log('ERROR', f"Failed to write tree file: {e}")

def run_script(script_path):
    try:
        result = subprocess.run(['python3', str(script_path)],
                                 capture_output=True, text=True, timeout=180,
                                 env={'OPENCLAW_WORKSPACE': str(WORKSPACE)})
        if result.returncode == 0:
            log('INFO', f"Successfully ran {script_path.name}")
        else:
            log('ERROR', f"Script {script_path.name} failed: {result.stderr.strip()}")
    except Exception as e:
        log('ERROR', f"Exception while running {script_path.name}: {e}")

def create_backups():
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M')
    for db_name in ['docs.db', 'tree.db']:
        src = DB_DIR / db_name
        if src.exists():
            backup_name = f"{timestamp}_{db_name}.bak"
            dest = BACKUP_DIR / backup_name
            try:
                copy2(src, dest)
                log('INFO', f"Backup created: {backup_name}")
            except Exception as e:
                log('ERROR', f"Failed to backup {db_name}: {e}")

def cleanup_backups(retention_days=3):
    cutoff = datetime.now() - timedelta(days=retention_days)
    for backup in BACKUP_DIR.iterdir():
        if backup.is_file():
            # Expect format YYYY-MM-DD_HH-MM_dbname.bak
            try:
                # Extract timestamp part before first underscore
                parts = backup.name.split('_')
                date_part = parts[0]
                time_part = parts[1]
                backup_dt = datetime.strptime(f"{date_part}_{time_part}", "%Y-%m-%d_%H-%M")
            except Exception:
                # If cannot parse, skip deletion
                continue
            if backup_dt < cutoff:
                try:
                    backup.unlink()
                    log('INFO', f"Deleted old backup: {backup.name}")
                except Exception as e:
                    log('ERROR', f"Failed to delete backup {backup.name}: {e}")

def main():
    # Run tree command and update file
    tree_output = run_tree()
    write_tree_file(tree_output)
    # Run database update scripts
    run_script(WORKSPACE / 'scripts' / 'update_docs_db.py')
    run_script(WORKSPACE / 'scripts' / 'tree_indexer_v2.py')
    # Create backups and cleanup
    create_backups()
    cleanup_backups()
    log('INFO', 'DB Maintainer cycle completed')

if __name__ == "__main__":
    main()
