#!/usr/bin/env python3
"""
Generate a simple tree view of the workspace up to a given depth.
This mimics the output of `tree -a -L 6` and writes the result to
`important/openclaw-tree.txt` with a header containing a timestamp.
"""
import os
import sys
import datetime
from pathlib import Path

# Determine workspace root (use env var if set, else default to /workspace)
workspace = Path(os.getenv('OPENCLAW_WORKSPACE', '/workspace'))
max_depth = 6

# Destination file
output_path = workspace / 'important' / 'openclaw-tree.txt'

# Header information
header = (
    f"# OpenClaw Workspace Tree\n"
    f"# Generated: {datetime.datetime.now().isoformat()}\n"
    f"# Command: tree -a -L {max_depth} {workspace}\n"
    "# This file is automatically generated by the heartbeat DB maintainer.\n\n"
)

lines = []

def walk(dir_path: Path, depth: int):
    if depth > max_depth:
        return
    try:
        entries = sorted(dir_path.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
    except PermissionError:
        return
    for entry in entries:
        prefix = "│   " * depth + "├── " if depth > 0 else ""
        name = entry.name + ("/" if entry.is_dir() else "")
        lines.append(prefix + name)
        if entry.is_dir():
            walk(entry, depth + 1)

# Start walking from the workspace root
walk(workspace, 0)

# Write to file
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(header)
    f.write('\n'.join(lines))
    f.write('\n')

print(f"Tree written to {output_path}")
