[Interface]
Address = 10.10.0.3/24
PrivateKey = QN0IpCUdp1nT7f+w07mFC9IxASJ1xjZ5gpZpx+ilaXo=
ListenPort = 51820

[Peer]
PublicKey = Tkqb+IHDsyHTBw/nKWQ91WFRF9/51XrLZe1FjC+zqzk=
AllowedIPs = 10.10.0.0/24
Endpoint = 152.53.145.65:51820
PersistentKeepalive = 25
