#!/usr/bin/env tclsh
# index.html — portiert nach tcl
# Quelle: html, Onboarding@main:development/preview-renders/hover-mock/index.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# Tcl 8.6 script to generate the HTML document
# Usage: tclsh this_script.tcl output_file.html

proc generate_html {} {
    set html {}

    # DOCTYPE and html tag
    append html "<!DOCTYPE html>\n"
    append html "<html lang=\"de\">\n"
    
    # Head section
    append html "<head>\n"
    append html "<meta charset=\"UTF-8\">\n"
    append html "<title>Hover-Preview Varianten · Vergleich</title>\n"
    
    # CSS Styles
    append html "<style>\n"
    append html "  :root {\n"
    append html "    --bg: #FAF8F4;\n"
    append html "    --ink: #1B1A17;\n"
    append html "    --accent: #A8542F;\n"
    append html "    --accent-2: #2E7D7B;\n"
    append html "    --font-display: 'Newsreader', Georgia, serif;\n"
    append html "    --font-body: 'Hanken Grotesk', -apple-system, sans-serif;\n"
    append html "    --font-mono: 'JetBrains Mono', monospace;\n"
    append html "  }\n"
    append html "  * { box-sizing: border-box; margin: 0; padding: 0; }\n"
    append html "  body {\n"
    append html "    font-family: var(--font-body);\n"
    append html "    background: var(--bg);\n"
    append html "    color: var(--ink);\n"
    append html "    padding: 32px 16px 80px;\n"
    append html "  }\n"
    append html "  h1 {\n"
    append html "    font-family: var(--font-display);\n"
    append html "    font-weight: 500;\n"
    append html "    font-size: 28px;\n"
    append html "    max-width: 1400px;\n"
    append html "    margin: 0 auto 12px;\n"
    append html "  }\n"
    append html "  .intro {\n"
    append html "    max-width: 1400px;\n"
    append html "    margin: 0 auto 32px;\n"
    append html "    color: #666;\n"
    append html "    font-size: 14px;\n"
    append html "    line-height: 1.5;\n"
    append html "  }\n"
    append html "  .grid {\n"
    append html "    display: grid;\n"
    append html "    gap: 32px;\n"
    append html "    max-width: 1400px;\n"
    append html "    margin: 0 auto;\n"
    append html "  }\n"
    append html "  .variant {\n"
    append html "    background: #000;\n"
    append html "    border-radius: 16px;\n"
    append html "    overflow: hidden;\n"
    append html "    box-shadow: 0 12px 40px rgba(0,0,0,0.15);\n"
    append html "  }\n"
    append html "  .variant-header {\n"
    append html "    background: #fff;\n"
    append html "    padding: 16px 24px;\n"
    append html "    display: flex;\n"
    append html "    align-items: center;\n"
    append html "    justify-content: space-between;\n"
    append html "    gap: 16px;\n"
    append html "    border-bottom: 1px solid #eee;\n"
    append html "  }\n"
    append html "  .variant-label {\n"
    append html "    font-family: var(--font-mono);\n"
    append html "    font-size: 11px;\n"
    append html "    letter-spacing: 0.2em;\n"
    append html "    text-transform: uppercase;\n"
    append html "    color: var(--accent);\n"
    append html "    font-weight: 600;\n"
    append html "  }\n"
    append html "  .variant-title {\n"
    append html "    font-family: var(--font-display);\n"
    append html "    font-size: 20px;\n"
    append html "    font-weight: 500;\n"
    append html "  }\n"
    append html "  .variant-desc {\n"
    append html "    font-size: 13px;\n"
    append html "    color: #666;\n"
    append html "    flex: 1;\n"
    append html "    text-align: right;\n"
    append html "  }\n"
    append html "  .scene {\n"
    append html "    position: relative;\n"
    append html "    aspect-ratio: 16 / 9;\n"
    append html "    background: url('bg.png') center/cover no-repeat;\n"
    append html "    overflow: hidden;\n"
    append html "  }\n"
    append html "  .orb {\n"
    append html "    position: absolute;\n"
    append html "    width: 12%;\n"
    append html "    aspect-ratio: 1;\n"
    append html "    left: 42%;\n"
    append html "    top: 55%;\n"
    append html "    transform: translate(-50%, -50%);\n"
    append html "    cursor: pointer;\n"
    append html "  }\n"
    append html "  .orb img { width: 100%; height: 100%; object-fit: contain; }\n"
    append html "\n"
    append html "  /* Variante 1: Karte daneben */\n"
    append html "  .card-preview {\n"
    append html "    position: absolute;\n"
    append html "    left: 55%;\n"
    append html "    top: 45%;\n"
    append html "    background: rgba(255,255,255,0.98);\n"
    append html "    padding: 16px 20px;\n"
    append html "    border-radius: 12px;\n"
    append html "    box-shadow: 0 8px 24px rgba(0,0,0,0.25);\n"
    append html "    width: 240px;\n"
    append html "    animation: slideIn 0.3s ease-out;\n"
    append html "  }\n"
    append html "  .card-preview .badge {\n"
    append html "    display: inline-block;\n"
    append html "    background: var(--accent-2);\n"
    append html "    color: white;\n"
    append html "    font-family: var(--font-mono);\n"
    append html "    font-size: 9px;\n"
    append html "    letter-spacing: 0.15em;\n"
    append html "    text-transform: uppercase;\n"
    append html "    padding: 3px 8px;\n"
    append html "    border-radius: 3px;\n"
    append html "    margin-bottom: 8px;\n"
    append html "  }\n"
    append html "  .card-preview h3 {\n"
    append html "    font-family: var(--font-display);\n"
    append html "    font-size: 18px;\n"
    append html "    font-weight: 500;\n"
    append html "    margin-bottom: 6px;\n"
    append html "    color: var(--ink);\n"
    append html "  }\n"
    append html "  .card-preview p {\n"
    append html "    font-size: 12px;\n"
    append html "    color: #555;\n"
    append html "    line-height: 1.4;\n"
    append html "  }\n"
    append html "  @keyframes slideIn {\n"
    append html "    from { opacity: 0; transform: translateX(-8px); }\n"
    append html "    to { opacity: 1; transform: translateX(0); }\n"
    append html "  }\n"
    append html "\n"
    append html "  /* Variante 2: Minimaler Tooltip */\n"
    append html "  .tooltip {\n"
    append html "    position: absolute;\n"
    append html "    left: 42%;\n"
    append html "    top: 46%;\n"
    append html "    transform: translate(-50%, -100%);\n"
    append html "    color: white;\n"
    append html "    text-shadow: 0 2px 12px rgba(0,0,0,0.8);\n"
    append html "    font-family: var(--font-display);\n"
    append html "    font-size: 20px;\n"
    append html "    font-weight: 500;\n"
    append html "    white-space: nowrap;\n"
    append html "    animation: fadeUp 0.3s ease-out;\n"
    append html "  }\n"
    append html "  @keyframes fadeUp {\n"
    append html "    from { opacity: 0; transform: translate(-50%, -80%); }\n"
    append html "    to { opacity: 1; transform: translate(-50%, -100%); }\n"
    append html "  }\n"
    append html "\n"
    append html "  /* Variante 3: Vollflächiges Overlay */\n"
    append html "  .full-overlay {\n"
    append html "    position: absolute;\n"
    append html "    inset: 0;\n"
    append html "    background: rgba(0,0,0,0.5);\n"
    append html "    backdrop-filter: blur(6px);\n"
    append html "    display: flex;\n"
    append html "    align-items: center;\n"
    append html "    justify-content: center;\n"
    append html "    animation: fadeIn 0.35s ease-out;\n"
    append html "  }\n"
    append html "  .full-overlay .panel {\n"
    append html "    background: rgba(255,255,255,0.98);\n"
    append html "    padding: 32px 40px;\n"
    append html "    border-radius: 20px;\n"
    append html "    max-width: 420px;\n"
    append html "    box-shadow: 0 20px 60px rgba(0,0,0,0.4);\n"
    append html "    text-align: center;\n"
    append html "  }\n"
    append html "  .full-overlay .badge {\n"
    append html "    display: inline-block;\n"
    append html "    background: var(--accent);\n"
    append html "    color: white;\n"
    append html "    font-family: var(--font-mono);\n"
    append html "    font-size: 10px;\n"
    append html "    letter-spacing: 0.2em;\n"
    append html "    text-transform: uppercase;\n"
    append html "    padding: 4px 10px;\n"
    append html "    border-radius: 4px;\n"
    append html "    margin-bottom: 14px;\n"
    append html "  }\n"
    append html "  .full-overlay h3 {\n"
    append html "    font-family: var(--font-display);\n"
    append html "    font-size: 28px;\n"
    append html "    font-weight: 500;\n"
    append html "    margin-bottom: 10px;\n"
    append html "    color: var(--ink);\n"
    append html "  }\n"
    append html "  .full-overlay p {\n"
    append html "    font-size: 14px;\n"
    append html "    color: #555;\n"
    append html "    line-height: 1.5;\n"
    append html "    margin-bottom: 20px;\n"
    append html "  }\n"
    append html "  .full-overlay .preview-img {\n"
    append html "    width: 100%;\n"
    append html "    aspect-ratio: 16/10;\n"
    append html "    background: linear-gradient(135deg, #A8542F, #2E7D7B);\n"
    append html "    border-radius: 8px;\n"
    append html "    margin-bottom: 16px;\n"
    append html "    display: flex;\n"
    append html "    align-items: center;\n"
    append html "    justify-content: center;\n"
    append html "    color: white;\n"
    append html "    font-family: var(--font-mono);\n"
    append html "    font-size: 11px;\n"
    append html "    letter-spacing: 0.15em;\n"
    append html "    opacity: 0.9;\n"
    append html "  }\n"
    append html "  @keyframes fadeIn {\n"
    append html "    from { opacity: 0; }\n"
    append html "    to { opacity: 1; }\n"
    append html "  }\n"
    append html "\n"
    append html "  .instruction {\n"
    append html "    text-align: center;\n"
    append html "    color: #999;\n"
    append html "    font-size: 12px;\n"
    append html "    margin-top: 16px;\n"
    append html "    font-family: var(--font-mono);\n"
    append html "    letter-spacing: 0.15em;\n"
    append html "    text-transform: uppercase;\n"
    append html "  }\n"
    append html "\n"
    append html "  @media (max-width: 900px) {\n"
    append html "    .card-preview { width: 180px; padding: 12px 14px; }\n"
    append html "    .card-preview h3 { font-size: 15px; }\n"
    append html "    .card-preview p { font-size: 11px; }\n"
    append html "    .tooltip { font-size: 15px; }\n"
    append html "    .full-overlay .panel { padding: 20px 24px; max-width: 300px; }\n"
    append html "    .full-overlay h3 { font-size: 20px; }\n"
    append html "  }\n"
    append html "</style>\n"
    
    # Font links
    append html "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
    append html "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
    append html "<link href=\"https://fonts.googleapis.com/css2?family=Newsreader:wght@400;500&family=Hanken+Grotesk:wght@400;500&family=JetBrains+Mono:wght@400;500&display=swap\" rel=\"stylesheet\">\n"
    append html "</head>\n"
    
    # Body section
    append html "<body>\n"
    append html "\n"
    append html "<h1>Hover-Preview · drei Varianten im Vergleich</h1>\n"
    append html "<p class=\"intro\">Gleiche Szene, gleiche Kugel-Position (Beispiel: Projekt-Kugel \"Weather-Check\").<br>Alle drei Varianten zeigen den Zustand <em>bei Maushover</em>. Welche soll ins Projekt?</p>\n"
    append html "\n"
    append html "<div class=\"grid\">\n"
    append html "\n"
    
    # Variante 1
    append html "  <!-- Variante 1 -->\n"
    append html "  <div class=\"variant\">\n"
    append html "    <div class=\"variant-header\">\n"
    append html "      <div>\n"
    append html "        <div class=\"variant-label\">Variante 1</div>\n"
    append html "        <div class=\"variant-title\">Karte daneben</div>\n"
    append html "      </div>\n"
    append html "      <div class=\"variant-desc\">Kompakte Card rechts der Kugel · Titel + Badge + kurze Beschreibung aus content.ts · dezent, nicht störend</div>\n"
    append html "    </div>\n"
    append html "    <div class=\"scene\">\n"
    append html "      <div class=\"orb\"><img src=\"orb-01-teal.png\" alt=\"\"></div>\n"
    append html "      <div class=\"card-preview\">\n"
    append html "        <span class=\"badge\">GitHub · Public</span>\n"
    append html "        <h3>Weather-Check</h3>\n"
    append html "        <p>Progressive Web App für lokale Wetterdaten mit Live-Radar und Push-Benachrichtigungen.</p>\n"
    append html "      </div>\n"
    append html "    </div>\n"
    append html "  </div>\n"
    append html "\n"
    
    # Variante 2
    append html "  <!-- Variante 2 -->\n"
    append html "  <div class=\"variant\">\n"
    append html "    <div class=\"variant-header\">\n"
    append html "      <div>\n"
    append html "        <div class=\"variant-label\">Variante 2</div>\n"
    append html "        <div class=\"variant-title\">Minimaler Tooltip</div>\n"
    append html "      </div>\n"
    append html "      <div class=\"variant-desc\">Nur der Titel schwebt über der Kugel · maximal reduziert · schnell erfassbar · lässt die Bildwirkung ungestört</div>\n"
    append html "    </div>\n"
    append html "    <div class=\"scene\">\n"
    append html "      <div class=\"orb\"><img src=\"orb-01-teal.png\" alt=\"\"></div>\n"
    append html "      <div class=\"tooltip\">Weather-Check</div>\n"
    append html "    </div>\n"
    append html "  </div>\n"
    append html "\n"
    
    # Variante 3
    append html "  <!-- Variante 3 -->\n"
    append html "  <div class=\"variant\">\n"
    append html "    <div class=\"variant-header\">\n"
    append html "      <div>\n"
    append html "        <div class=\"variant-label\">Variante 3</div>\n"
    append html "        <div class=\"variant-title\">Vollflächiges Overlay</div>\n"
    append html "      </div>\n"
    append html "      <div class=\"variant-desc\">Zentrales Modal mit Preview-Bild + Titel + Beschreibung · prominent · lädt zum Klicken ein · verdeckt aber Szene</div>\n"
    append html "    </div>\n"
    append html "    <div class=\"scene\">\n"
    append html "      <div class=\"orb\"><img src=\"orb-01-teal.png\" alt=\"\"></div>\n"
    append html "      <div class=\"full-overlay\">\n"
    append html "        <div class=\"panel\">\n"
    append html "          <div class=\"preview-img\">PROJEKT-PREVIEW</div>\n"
    append html "          <span class=\"badge\">GitHub · Public</span>\n"
    append html "          <h3>Weather-Check</h3>\n"
    append html "          <p>Progressive Web App für lokale Wetterdaten mit Live-Radar und Push-Benachrichtigungen.</p>\n"
    append html "        </div>\n"
    append html "      </div>\n"
    append html "    </div>\n"
    append html "  </div>\n"
    append html "\n"
    append html "</div>\n"
    append html "\n"
    append html "<p class=\"instruction\">Sag mir welche Variante — dann baue ich sie ins Frontend ein.</p>\n"
    append html "\n"
    append html "</body>\n"
    append html "</html>\n"
    
    return $html
}

# Main execution
if {$argc != 1} {
    puts "Usage: $argv0 output_file.html"
    exit 1
}

set output_file [lindex $argv 0]
set html_content [generate_html]

# Write to file
set fh [open $output_file w]
puts -nonewline $fh $html_content
close $fh

puts "HTML file generated: $output_file"
