#!/usr/bin/env tclsh
# OnboardingandProjects_canvablock.html — portiert nach tcl
# Quelle: html, Onboarding@main:docs/appendix/claude-cowork/OnboardingandProjects_canvablock.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# Tcl 8.6 script to generate OnboardingandProjects_canvablock.html
# This script creates the complete HTML document structure programmatically

proc generate_html {} {
    set html ""
    
    # Document type and root element
    append html "<!DOCTYPE html>\n"
    append html "<html>\n"
    
    # Head section
    append html [generate_head]
    
    # Body section
    append html [generate_body]
    
    # Close root element
    append html "</html>\n"
    
    return $html
}

proc generate_head {} {
    set head ""
    append head "<head>\n"
    append head "<title>Onboarding and Projects</title>\n"
    append head "<meta charset=\"utf-8\">\n"
    append head "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    append head [generate_script]
    append head "</head>\n"
    return $head
}

proc generate_script {} {
    set script ""
    append script "<script>\n"
    append script "// GENERATED from dc-runtime/src/*.ts — do not edit. Rebuild with `cd dc-runtime && bun run build`.\n"
    append script "\"use strict\";\n"
    append script "(() => {\n"
    append script "  var __defProp = Object.defineProperty;\n"
    append script "  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;\n"
    append script "  var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== \"symbol\" ? key + \"\" : key, value);\n"
    append script "\n"
    append script "  // src/react.ts\n"
    append script "  function getReact() {\n"
    append script "    const R = window.React;\n"
    append script "    if (!R) throw new Error(\"dc-runtime: window.React is not available yet\");\n"
    append script "    return R;\n"
    append script "  }\n"
    append script "  function getReactDOM() {\n"
    append script "    const RD = window.ReactDOM;\n"
    append script "    if (!RD) throw new Error(\"dc-runtime: window.ReactDOM is not available yet\");\n"
    append script "    return RD;\n"
    append script "  }\n"
    append script "  var h = ((...args) => getReact().createElement(\n"
    append script "    ...args\n"
    append script "  ));\n"
    append script "\n"
    append script "  // src/parse.ts\n"
    append script "  function parseDcDocument(doc) {\n"
    append script "    const dc = doc.querySelector(\"x-dc\");\n"
    append script "    if (!dc) return null;\n"
    append script "    const scriptEl = doc.querySelector(\"script[data-dc-script]\");\n"
    append script "    const { props, preview } = parseDataProps(\n"
    append script "      scriptEl?.getAttribute(\"data-props\") ?? null\n"
    append script "    );\n"
    append script "    return {\n"
    append script "      template: dc.innerHTML,\n"
    append script "      js: scriptEl ? scriptEl.textContent || \"\" : \"\",\n"
    append script "      props,\n"
    append script "      preview\n"
    append script "    };\n"
    append script "  }\n"
    append script "  function parseDcText(src) {\n"
    append script "    const openMatch = /<x-dc(?:\\s[^>]*)?>/.exec(src);\n"
    append script "    if (!openMatch) return null;\n"
    append script "    const close = src.lastIndexOf(\"</x-dc>\");\n"
    append script "    if (close === -1 || close < openMatch.index) return null;\n"
    append script "    const template = src.slice(openMatch.index + openMatch[0].length, close);\n"
    append script "    const doc = new DOMParser().parseFromString(src, \"text/html\");\n"
    append script "    const scriptEl = doc.querySelector(\"script[data-dc-script]\");\n"
    append script "    const { props, preview } = parseDataProps(\n"
    append script "      scriptEl?.getAttribute(\"data-props\") ?? null\n"
    append script "    );\n"
    append script "    return {\n"
    append script "      template,\n"
    append script "      js: scriptEl ? scriptEl.textContent || \"\" : \"\",\n"
    append script "      props,\n"
    append script "      preview\n"
    append script "    };\n"
    append script "  }\n"
    append script "  function parseDataProps(raw) {\n"
    append script "    if (!raw) return { props: null, preview: null };\n"
    append script "    let parsed;\n"
    append script "    try {\n"
    append script "      parsed = JSON.parse(raw);\n"
    append script "    } catch {\n"
    append script "      return { props: null, preview: null };\n"
    append script "    }\n"
    append script "    if (!parsed || typeof parsed !== \"object\" || Array.isArray(parsed)) {\n"
    append script "      return { props: null, preview: null };\n"
    append script "    }\n"
    append script "    const obj = parsed;\n"
    append script "    const preview = obj.\$preview && typeof obj.\$preview === \"object\" ? obj.\$preview : null;\n"
    append script "    const rest = {};\n"
    append script "    for (const k of Object.keys(obj)) {\n"
    append script "      if (k[0] !== \"\$\") rest[k] = obj[k];\n"
    append script "    }\n"
    append script "    return { props: Object.keys(rest).length ? rest : null, preview };\n"
    append script "  }\n"
    append script "  function dcNameFromPath(pathname) {\n"
    append script "    let p = pathname || \"\";\n"
    append script "    try {\n"
    append script "      p = decodeURIComponent(p);\n"
    append script "    } catch {\n"
    append script "    }\n"
    append script "    const base = p.split(\"/\").pop() || \"Root\";\n"
    append script "    return base.replace(/\\.dc\\.html\$/, \"\").replace(/\\.html?\$/, \"\") || \"Root\";\n"
    append script "  }\n"
    append script "\n"
    append script "  // src/boot.ts\n"
    append script "  var BASE_CSS = `\n"
    append script "    .sc-placeholder{background:rgba(255,255,255,.3);border:1px solid rgba(0,0,0,.5);\n"
    append script "      border-radius:2px;box-sizing:border-box;overflow:hidden}\n"
    append script "    @keyframes sc-shine{0%{background-position:100% 50%}100%{background-position:0% 50%}}\n"
    append script "    html.sc-dc-streaming .sc-placeholder,\n"
    append script "    html.sc-dc-streaming .sc-interp.sc-missing{position:relative;\n"
    append script "      background:color-mix(in srgb,currentColor 5%,transparent);\n"
    append script "      border-color:transparent}\n"
    append script "    html.sc-dc-streaming .sc-placeholder::before,\n"
    append script "    html.sc-dc-streaming .sc-interp.sc-missing::before{content:'';\n"
    append script "      position:absolute;inset:0;pointer-events:none;\n"
    append script "      background:linear-gradient(90deg,rgba(217,119,87,0) 25%,rgba(247,225,211,.95) 37%,rgba(217,119,87,0) 63%);\n"
    append script "      background-size:400% 100%;animation:sc-shine 1.4s ease infinite}\n"
    append script "    html.sc-dc-streaming .sc-placeholder:nth-child(n+9 of .sc-placeholder)::before,\n"
    append script "    html.sc-dc-streaming .sc-interp.sc-missing:nth-child(n+9 of .sc-interp.sc-missing)::before{animation:none;\n"
    append script "      background:color-mix(in srgb,currentColor 8%,transparent)}\n"
    append script "    .sc-placeholder-error{padding:4px 8px;font:11px/1.4 ui-monospace,monospace;\n"
    append script "      color:rgba(0,0,0,.7);word-break:break-word}\n"
    append script "    .sc-interp.sc-missing{display:inline-block;width:2em;height:1em;overflow:hidden;\n"
    append script "      vertical-align:text-bottom;background:rgba(255,255,255,.3);border:1px solid rgba(0,0,0,.5);\n"
    append script "      border-radius:2px;box-sizing:border-box;color:transparent;\n"
    append script "      user-select:none}\n"
    append script "    .sc-interp.sc-unresolved{font-family:ui-monospace,monospace;font-size:.85em;\n"
    append script "      color:rgba(0,0,0,.5);background:rgba(0,0,0,.05);border-radius:3px;\n"
    append script "      padding:0 3px}\n"
    append script "    .sc-host.sc-has-error{position:relative}\n"
    append script "    .sc-logic-error{position:absolute;top:8px;left:8px;z-index:2147483647;max-width:60ch;\n"
    append script "      padding:6px 10px;background:#b00020;color:#fff;font:12px/1.4 ui-monospace,monospace;\n"
    append script "      border-radius:4px;white-space:pre-wrap;pointer-events:none}\n"
    append script "    /* Mirrors PRINT_BASELINE_CSS in apps/web deck-stage-export.ts \\u2014 keep both\n"
    append script "       in sync until dc-runtime regains a build step. */\n"
    append script "    @media print {\n"
    append script "      @page { margin: 0.5cm; }\n"
    append script "      section, article, figure, table { break-inside: avoid; }\n"
    append script "      *, *::before, *::after {\n"
    append script "        print-color-adjust: exact; -webkit-print-color-adjust: exact;\n"
    append script "        backdrop-filter: none !important; -webkit-backdrop-filter: none !important;\n"
    append script "        animation-delay: -99s !important; animation-duration: .001s !important;\n"
    append script "        animation-iteration-count: 1 !important; animation-fill-mode: both !important;\n"
    append script "        animation-play-state: running !important; transition-duration: 0s !important;\n"
    append script "      }\n"
    append script "    }\n"
    append script "  `;\n"
    append script "  var FULL_PAGE_CSS = \"html,body{height:100%;margin:0}#dc-root,#dc-root>.sc-host{height:100%}\";\n"
    append script "  function rootNameForDocument(doc, loc) {\n"
    append script "    let bootPath = loc.pathname || \"\";\n"
    append script "    if (!/\\.dc\\.html?$/i.test(safeDecode(bootPath))) {\n"
    append script "      try {\n"
    append script "        bootPath = new URL(doc.baseURI || \"/\").pathname;\n"
    append script "      } catch {\n"
    append script "      }\n"
    append script "    }\n"
    append script "    return dcNameFromPath(bootPath);\n"
    append script "  }\n"
    append script "  function safeDecode(s) {\n"
    append script "    try {\n"
    append script "      return decodeURIComponent(s);\n"
    append script "    } catch {\n"
    append script "      return s;\n"
    append script "    }\n"
    append script "  }\n"
    append script "  function boot(runtime, doc = document) {\n"
    append script "    const parsed = parseDcDocument(doc);\n"
    append script "    if (!parsed) return null;\n"
    append script "    const React = getReact();\n"
    append script "    const rootName = rootNameForDocument(doc, location);\n"
    append script "    runtime.markFetched(rootName);\n"
    append script "    runtime.adoptParsed(rootName, parsed);\n"
    append script "    fetch(location.href).then((res) => res.ok ? res.text() : \"\").then((t) => {\n"
    append script "      const raw = t ? parseDcText(t) : null;\n"
    append script "      if (raw?.template) runtime.updateHtml(rootName, raw.template);\n"
    append script "    }).catch(() => {\n"
    append script "    });\n"
    append script "    const dc = doc.querySelector(\"x-dc\");\n"
    append script "    const hostEl = doc.createElement(\"div\");\n"
    append script "    hostEl.id = \"dc-root\";\n"
    append script "    dc.replaceWith(hostEl);\n"
    append script "    if (!parsed.preview) {\n"
    append script "      const s = doc.createElement(\"style\");\n"
    append script "      s.textContent = FULL_PAGE_CSS;\n"
    append script "      doc.head.appendChild(s);\n"
    append script "    }\n"
    append script "    const Root = runtime.getDC(rootName);\n"
    append script "    const entry = runtime.registry.get(rootName);\n"
    append script "    function StandaloneRoot() {\n"
    append script "      const [, setTick] = React.useState(0);\n"
    append script "      React.useEffect(() => {\n"
    append script "        const sub = () => setTick((n) => n + 1);\n"
    append script "        entry.subs.add(sub);\n"
    append script "        return () => {\n"
    append script "          entry.subs.delete(sub);\n"
    append script "        };\n"
    append script "      }, []);\n"
    append script "      return h(Root, entry.propOverrides || null);\n"
    append script "    }\n"
    append script "    const ReactDOM = getReactDOM();\n"
    append script "    if (ReactDOM.createRoot)\n"
    append script "      ReactDOM.createRoot(hostEl).render(h(StandaloneRoot));\n"
    append script "    else ReactDOM.render(h(StandaloneRoot), hostEl);\n"
    append script "    return rootName;\n"
    append script "  }\n"
    append script "\n"
    append script "  // src/expr.ts\n"
    append script "  var IDENT_RE = /^[A-Za-z_\$][A-Za-z0-9_\$]*/;\n"
    append script "  var NUMBER_RE = /^-?\\d+(\\.\\d+)?$/;\n"
    append script "  function resolve(vals, src) {\n"
    append script "    const expr = String(src).trim();\n"
    append script "    if (!expr) return void 0;\n"
    append script "    if (expr[0] === \"(\" && expr[expr.length - 1] === \")\" && parensWrapWhole(expr)) {\n"
    append script "      return resolve(vals, expr.slice(1, -1));\n"
    append script "    }\n"
    append script "    const eq = findTopLevelEquality(expr);\n"
    append script "    if (eq) {\n"
    append script "      const lv = resolve(vals, expr.slice(0, eq.index));\n"
    append script "      const rv = resolve(vals, expr.slice(eq.index + eq.op.length));\n"
    append script "      switch (eq.op) {\n"
    append script "        case \"===\":\n"
    append script "          return lv === rv;\n"
    append script "        case \"!==\":\n"
    append script "          return lv !== rv;\n"
    append script "        case \"==\":\n"
    append script "          return lv == rv;\n"
    append script "        default:\n"
    append script "          return lv != rv;\n"
    append script "      }\n"
    append script "    }\n"
    append script "    if (expr[0] === \"!\") return !resolve(vals, expr.slice(1));\n"
    append script "    if (expr === \"true\") return true;\n"
    append script "    if (expr === \"false\") return false;\n"
    append script "    if (expr === \"null\") return null;\n"
    append script "    if (expr === \"undefined\") return void 0;\n"
    append script "    if (NUMBER_RE.test(expr)) return Number(expr);\n"
    append script "    if (expr.length >= 2 && (expr[0] === \"\\\"\" || expr[0] === \"'\") && expr[expr.length - 1] === expr[0]) {\n"
    append script "      return expr.slice(1, -1);\n"
    append script "    }\n"
    append script "    return resolvePath(vals, expr);\n"
    append script "  }\n"
    append script "  function parensWrapWhole(expr) {\n"
    append script "    let depth = 0;\n"
    append script "    for (let i = 0; i < expr.length - 1; i++) {\n"
    append script "      if (expr[i] === \"(\") depth++;\n"
    append script "      else if (expr[i] === \")\") {\n"
    append script "        depth--;\n"
    append script "        if (depth === 0) return false;\n"
    append script "      }\n"
    append script "    }\n"
    append script "    return true;\n"
    append script "  }\n"
    append script "  function findTopLevelEquality(expr) {\n"
    append script "    let depth = 0;\n"
    append script "    for (let i = 0; i < expr.length; i++) {\n"
    append script "      const c = expr[i];\n"
    append script "      if (c === \"[\" || c === \"(\") depth++;\n"
    append script "      else if (c === \"]\" || c === \")\") depth--;\n"
    append script "      else if (depth === 0 && (c === \"=\" || c === \"!\") && expr[i + 1] === \"=\") {\n"
    append script "        if (i > 0 && (expr[i - 1] === \"=\" || expr[i - 1] === \"!\")) continue;\n"
    append script "        if (!expr.slice(0, i).trim()) continue;\n"
    append script "        const op = expr[i + 2] === \"=\" ? c + \"==\" : c + \"=\";\n"
    append script "        return { index: i, op };\n"
    append script "      }\n"
    append script "    }\n"
    append script "    return null;\n"
    append script "  }\n"
    append script "  function resolvePath(vals, expr) {\n"
    append script "    const head = expr.match(IDENT_RE);\n"
    append script "    if (!head) return void 0;\n"
    append script "    let cur = vals == null ? void 0 : vals[head[0]];\n"
    append script "    let i = head[0].length;\n"
    append script "    while (i < expr.length) {\n"
    append script "      if (expr[i] === \".\") {\n"
    append script "        const m = expr.slice(i + 1).match(IDENT_RE) || expr.slice(i + 1).match(/^\\d+/);\n"
    append script "        if (!m) return void 0;\n"
    append script "        cur = cur == null ? void 0 : cur[m[0]];\n"
    append script "        i += 1 + m[0].length;\n"
    append script "      } else if (expr[i] === \"[\") {\n"
    append script "        let depth = 1;\n"
    append script "        let j = i + 1;\n"
    append script "        while (j < expr.length && depth > 0) {\n"
    append script "          if (expr[j] === \"[\") depth++;\n"
    append script "          else if (expr[j] === \"]\") {\n"
    append script "            depth--;\n"
    append script "            if (depth === 0) break;\n"
    append script "          }\n"
    append script "          j++;\n"
    append script "        }\n"
    append script "        if (depth !== 0) return void 0;\n"
    append script "        const key = resolve(vals, expr.slice(i + 1, j));\n"
    append script "        cur = cur == null ? void 0 : cur[key];\n"
    append script "        i = j + 1;\n"
    append script "      } else {\n"
    append script "        return void 0;\n"
    append script "      }\n"
    append script "    }\n"
    append script "    return cur;\n"
    append script "  }\n"
    append script "\n"
    append script "  // src/encode.ts\n"
    append script "  var CAMEL_ATTR = \"sc-camel-\";\n"
    append script "  var RAW_WRAP = {\n"
    append script "    select: \"sc-raw-select\",\n"
    append script "    table: \"sc-raw-table\",\n"
    append script "    tbody: \"sc-raw-tbody\",\n"
    append script "    thead: \"sc-raw-thead\",\n"
    append script "    tfoot: \"sc-raw-tfoot\",\n"
    append script "    tr: \"sc-raw-tr\",\n"
    append script "    td: \"sc-raw-td\",\n"
    append script "    th: \"sc-raw-th\",\n"
    append script "    caption: \"sc-raw-caption\"\n"
    append script "  };\n"
    append script "  var RAW_UNWRAP = Object.fromEntries(\n"
    append script "    Object.entries(RAW_WRAP).map(([k, v]) => [v, k])\n"
    append script "  );\n"
    append script "  var EVENT_MAP = {\n"
    append script "    onclick: \"onClick\",\n"
    append script "    onchange: \"onChange\",\n"
    append script "    oninput: \"onInput\",\n"
    append script "    onsubmit: \"onSubmit\",\n"
    append script "    onkeydown: \"onKeyDown\",\n"
    append script "    onkeyup: \"onKeyUp\",\n"
    append script "    onkeypress: \"onKeyPress\",\n"
    append script "    onmousedown: \"onMouseDown\",\n"
    append script "    onmouseup: \"onMouseUp\",\n"
    append script "    onmouseenter: \"onMouseEnter\",\n"
    append script "    onmouseleave: \"onMouseLeave\",\n"
    append script "    onfocus: \"onFocus\",\n"
    append script "    onblur: \"onBlur\",\n"
    append script "    ondoubleclick: \"onDoubleClick\",\n"
    append script "    oncontextmenu: \"onContextMenu\"\n"
    append script "  };\n"
    append script "  var ATTRS = `(?:[^>\"']|\"[^\"]*\"|'[^']*')*`;\n"
    append script "  var IMPORT_SELF_CLOSE_RE = new RegExp(\n"
    append script "    \"<(x-import|dc-import)(\" + ATTRS + \")/>\",\n"
    append script "    \"gi\"\n"
    append script "  );\n"
    append script "  var CAMEL_ATTR_RE = /(\\s)([a-z]+[A-Z][A-Za-z0-9]*)(\\s*=)/g;\n"
    append script "  function encodeCase(html) {\n"
    append script "    html = html.replace(\n"
    append script "      IMPORT_SELF_CLOSE_RE,\n"
    append script "      (_, t, a) => \"<\" + t + a + \"></\" + t + \">\"\n"
    append script "    );\n"
    append script "    html = html.replace(/<helmet(\\s|>)/gi, \"<sc-helmet\$1\");\n"
    append script "    html = html.replace(/<\\/helmet\\s*>/gi, \"</sc-helmet>\");\n"
    append script "    html = html.replace(\n"
    append script "      CAMEL_ATTR_RE,\n"
    append script "      (_, sp, name, eq) => sp + CAMEL_ATTR + name.replace(/[A-Z]/g, (c) => \"-\" + c.toLowerCase()) + eq\n"
    append script "    );\n"
    append script "    for (const [real, alias] of Object.entries(RAW_WRAP)) {\n"
    append script "      html = html.replace(\n"
    append script "        new RegExp(\"(</?)\" + real + \"(?=[\\\\s>])\", \"gi\"),\n"
    append script "        \"\$1\" + alias\n"
    append script "      );\n"
    append script "    }\n"
    append script "    return html;\n"
    append script "  }\n"
    append script "  function kebabToCamel(s) {\n"
    append script "    return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());\n"
    append script "  }\n"
    append script "  function cssToObj(css) {\n"
    append script "    const o = {};\n"
    append script "    for (const decl of css.split(\";\")) {\n"
    append script "      const i = decl.indexOf(\":\");\n"
    append script "      if (i < 0) continue;\n"
    append script "      const prop = decl.slice(0, i).trim();\n"
    append script "      o[prop.startsWith(\"--\") ? prop : kebabToCamel(prop)] = decl.slice(i + 1).trim();\n"
    append script "    }\n"
    append script "    return o;\n"
    append script "  }\n"
    append script "  function compileAttr(raw) {\n"
    append script "    const whole = raw.match(/^\\s*\\{\\{([\\s\\S]+?)\\}\\}\\s*\$/);\n"
    append script "    if (whole) {\n"
    append script "      const path = whole[1];\n"
    append script "      return (vals) => resolve(vals, path);\n"
    append script "    }\n"
    append script "    if (raw.includes(\"{{\")) {\n"
    append script "      const parts = raw.split(/\\{\\{([\\s\\S]+?)\\}\\}/g);\n"
    append script "      return (vals) => parts.map((s, i) => i & 1 ? resolve(vals, s) ?? \"\" : s).join(\"\");\n"
    append script "    }\n"
    append script "    return () => raw;\n"
    append script "  }\n"
    append script "\n"
    append script "  // src/compile.ts\n"
    append script "  function collectProps(node, isComponent, host) {\n"
    append script "    const propGetters = [];\n"
    append script "    const pseudoClasses = [];\n"
    append script "    let hintSize = null;\n"
    append script "    for (const { name, value } of [...node.attributes]) {\n"
    append script "      if (name === \"sc-name\" || name === \"data-dc-tpl\") continue;\n"
    append script "      let key = name;\n"
    append script "      if (key.startsWith(CAMEL_ATTR))\n"
    append script "        key = kebabToCamel(key.slice(CAMEL_ATTR.length));\n"
    append script "      if (key === \"hint-size\") {\n"
    append script "        hintSize = value;\n"
    append script "        continue;\n"
    append script "      }\n"
    append script "      if (key.startsWith(\"style-\")) {\n"
    append script "        pseudoClasses.push(host.pseudoClass(key.slice(6), value));\n"
    append script "        continue;\n"
    append script "      }\n"
    append script "      if (isComponent) {\n"
    append script "        if (key.includes(\"-\")) key = kebabToCamel(key);\n"
    append script "      } else {\n"
    append script "        if (key === \"class\") key = \"className\";\n"
    append script "        else if (key === \"for\") key = \"htmlFor\";\n"
    append script "        else if (key.startsWith(\"on\"))\n"
    append script "          key = EVENT_MAP[key] || \"on\" + key[2].toUpperCase() + key.slice(3);\n"
    append script "      }\n"
    append script "      propGetters.push([key, compileAttr(value)]);\n"
    append script "    }\n"
    append script "    return { propGetters, pseudoClasses, hintSize };\n"
    append script "  }\n"
    append script "  var HOST_STYLE_PROPS = /* @__PURE__ */ new Set([\n"
    append script "    \"position\",\n"
    append script "    \"left\",\n"
    append script "    \"right\",\n"
    append script "    \"top\",\n"
    append script "    \"bottom\",\n"
    append script "    \"inset\",\n"
    append script "    \"width\",\n"
    append script "    \"height\",\n"
    append script "    \"z-index\",\n"
    append script "    \"transform\"\n"
    append script "  ]);\n"
    append script "  function hostPositionStyle(style) {\n"
    append script "    const all = typeof style === \"string\" ? cssToObj(style) : style != null && typeof style === \"object\" ? style : null;\n"
    append script "    if (!all) return void 0;\n"
    append script "    const out = {};\n"
    append script "    for (const [k, v] of Object.entries(all)) {\n"
    append script "      const kebab = k.replace(/[A-Z]/g, (c) => \"-\" + c.toLowerCase());\n"
    append script "      if (HOST_STYLE_PROPS.has(kebab)) out[k] = v;\n"
    append script "    }\n"
    append script "    return Object.keys(out).length ? out : void 0;\n"
    append script "  }\n"
    append script "  function compileTemplate(html, host) {\n"
    append script "    const tpl = document.createElement(\"template\");\n"
    append script "    //! nosemgrep: direct-inner-html-assignment\n"
    append script "    tpl.innerHTML = encodeCase(html);\n"
    append script "    let tplN = 0;\n"
    append script "    (function stamp(node) {\n"
    append script "      if (node.nodeType === Node.ELEMENT_NODE) {\n"
    append script "        node.setAttribute(\"data-dc-tpl\", String(tplN++));\n"
    append script "      }\n"
    append script "      for (const c of node.childNodes) stamp(c);\n"
    append script "    })(tpl.content);\n"
    append script "    const builders = walkChildren(tpl.content, host);\n"
    append script "    const render = ((vals, ctx) => builders.map((b, i) => b(vals || {}, ctx, i)));\n"
    append script "    render.__annotated = tpl.innerHTML;\n"
    append script "    return render;\n"
    append script "  }\n"
    append script "  function walkChildren(node, host) {\n"
    append script "    return [...node.childNodes].map((c) => walk(c, host)).filter((b) => b != null);\n"
    append script "  }\n"
    append script "  function walk(node, host) {\n"
    append script "    if (node.nodeType === Node.TEXT_NODE) return walkText(node);\n"
    append script "    if (node.nodeType !== Node.ELEMENT_NODE) return null;\n"
    append script "    const el = node;\n"
    append script "    const tag = el.tagName.toLowerCase();\n"
    append script "    if (tag === \"sc-for\") return walkFor(el, host);\n"
    append script "    if (tag === \"sc-if\") return walkIf(el, host);\n"
    append script "    if (tag === \"x-import\") return walkXImport(el, host);\n"
    append script "    if (tag === \"sc-helmet\") return host.helmet(el);\n"
    append script "    if (tag === \"dc-import\") return walkComponent(el, host);\n"
    append script "    return walkElement(el, host);\n"
    append script "  }\n"
    append script "  var warnedHoles = /* @__PURE__ */ new Set();\n"
    append script "  function warnUnresolved(ctx, what) {\n"
    append script "    const key = (ctx?.__name || \"?\") + \"\\0\" + what;\n"
    append script "    if (warnedHoles.has(key)) return;\n"
    append script "    warnedHoles.add(key);\n"
    append script "    console.warn(\"[dc-runtime] \" + (ctx?.__name || \"template\") + \": \" + what);\n"
    append script "  }\n"
    append script "  function walkText(node) {\n"
    append script "    const txt = node.nodeValue ?? \"\";\n"
    append script "    if (!txt.includes(\"{{\")) {\n"
    append script "      if (!txt.trim() && !txt.includes(\" \")) return null;\n"
    append script "      return () => txt;\n"
    append script "    }\n"
    append script "    const parts = txt.split(/\\{\\{([\\s\\S]+?)\\}\\}/g);\n"
    append script "    return (vals, ctx, key) => h(\n"
    append script "      getReact().Fragment,\n"
    append script "      { key },\n"
    append
