#!/usr/bin/env tclsh
# tiktok-embed-viewer.html — portiert nach tcl
# Quelle: html, Projects@Telegram-Monitor:plugin/tiktok-embed-viewer.html
# Erzeugt: 2026-08-19 durch ABSTRACTIONS_MANAGER.py

# Ported from HTML to Tcl 8.6
# Generates the complete HTML document structure programmatically

proc generate_html {} {
    set html [list]
    
    # DOCTYPE and html tag
    lappend html "<!DOCTYPE html>"
    lappend html "<html lang=\"de\">"
    
    # Head section
    lappend html "<head>"
    lappend html "<meta charset=\"utf-8\">"
    lappend html "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
    lappend html "<title>TikTok Live — Embed-Viewer</title>"
    lappend html "<style>"
    lappend html "  :root{"
    lappend html "    --bg:#0f1115; --card:#171a21; --line:#262b36; --text:#f2f4f8; --muted:#9aa3b2;"
    lappend html "    --accent:#25f4ee; --accent2:#fe2c55; --ok:#22c55e; --off:#6b7280;"
    lappend html "    color-scheme: dark;"
    lappend html "  }"
    lappend html "  @media (prefers-color-scheme: light){"
    lappend html "    :root{ --bg:#f6f7f9; --card:#fff; --line:#e3e6ea; --text:#16191d; --muted:#6b7280; }"
    lappend html "  }"
    lappend html "  *{box-sizing:border-box}"
    lappend html "  body{margin:0;background:var(--bg);color:var(--text);"
    lappend html "       font:15px/1.5 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif}"
    lappend html "  .wrap{max-width:1120px;margin:0 auto;padding:16px}"
    lappend html "  header{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:14px}"
    lappend html "  h1{font-size:17px;margin:0;font-weight:650}"
    lappend html "  .badge{display:inline-flex;align-items:center;gap:6px;font-size:12px;font-weight:700;"
    lappend html "         padding:3px 10px;border-radius:99px;background:#2a2f3a;color:var(--muted)}"
    lappend html "  .badge.live{background:var(--accent2);color:#fff}"
    lappend html "  .badge .dot{width:7px;height:7px;border-radius:50%;background:currentColor}"
    lappend html "  .badge.live .dot{animation:pulse 1.6s infinite}"
    lappend html "  @keyframes pulse{0%,100%{opacity:1}50%{opacity:.25}}"
    lappend html "  input,select,button{font:inherit;border-radius:8px;border:1px solid var(--line);"
    lappend html "                      background:var(--card);color:var(--text);padding:8px 11px}"
    lappend html "  button{cursor:pointer;font-weight:600}"
    lappend html "  button.primary{background:var(--accent2);border-color:var(--accent2);color:#fff}"
    lappend html "  .row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:12px}"
    lappend html "  .grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:14px}"
    lappend html "  @media (max-width:860px){ .grid{grid-template-columns:1fr} }"
    lappend html "  .card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px}"
    lappend html "  .player{position:relative;width:100%;aspect-ratio:9/16;max-height:78vh;background:#000;"
    lappend html "          border-radius:12px;overflow:hidden;border:1px solid var(--line)}"
    lappend html "  .player iframe{position:absolute;inset:0;width:100%;height:100%;border:0}"
    lappend html "  .placeholder{position:absolute;inset:0;display:flex;flex-direction:column;gap:8px;"
    lappend html "               align-items:center;justify-content:center;color:var(--muted);text-align:center;padding:24px}"
    lappend html "  h2{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);"
    lappend html "     margin:0 0 8px;font-weight:650}"
    lappend html "  .meta{color:var(--muted);font-size:13px}"
    lappend html "  .stream{display:flex;gap:10px;padding:7px 0;border-bottom:1px solid var(--line);font-size:13.5px}"
    lappend html "  .stream:last-child{border-bottom:0}"
    lappend html "  .stream .when{color:var(--muted);white-space:nowrap;font-variant-numeric:tabular-nums}"
    lappend html "  .stream .t{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    lappend html "  .stream.now{color:var(--accent2);font-weight:600}"
    lappend html "  .note{font-size:12.5px;color:var(--muted);margin-top:10px;line-height:1.45}"
    lappend html "  a{color:var(--accent2)} a:hover{text-decoration:underline}"
    lappend html "  .err{background:#3a1d22;border:1px solid #5c2a33;color:#ffb4c0;padding:9px 12px;"
    lappend html "       border-radius:8px;font-size:13px;margin-bottom:10px}"
    lappend html "  @media (prefers-color-scheme: light){ .err{background:#fdeceb;border-color:#f5c6c2;color:#b91c1c} }"
    lappend html "</style>"
    lappend html "</head>"
    
    # Body section
    lappend html "<body>"
    lappend html "<div class=\"wrap\">"
    lappend html "  <header>"
    lappend html "    <h1>TikTok Live — Embed-Viewer</h1>"
    lappend html "    <span class=\"badge\" id=\"badge\"><span class=\"dot\"></span><span id=\"badgeText\">unbekannt</span></span>"
    lappend html "    <span class=\"meta\" id=\"checked\"></span>"
    lappend html "  </header>"
    lappend html ""
    lappend html "  <div class=\"row\">"
    lappend html "    <input id=\"user\" placeholder=\"@name\" style=\"min-width:180px\">"
    lappend html "    <button class=\"primary\" id=\"go\">Anzeigen</button>"
    lappend html "    <select id=\"every\">"
    lappend html "      <option value=\"60\">Status alle 60 s</option>"
    lappend html "      <option value=\"120\" selected>alle 2 min</option>"
    lappend html "      <option value=\"300\">alle 5 min</option>"
    lappend html "      <option value=\"0\">nur manuell</option>"
    lappend html "    </select>"
    lappend html "    <label class=\"meta\"><input type=\"checkbox\" id=\"notify\"> bei Livegang benachrichtigen</label>"
    lappend html "    <label class=\"meta\"><input type=\"checkbox\" id=\"autoplay\" checked> Player automatisch laden</label>"
    lappend html "    <button id=\"force\">Player trotzdem laden</button>"
    lappend html "  </div>"
    lappend html ""
    lappend html "  <div id=\"error\"></div>"
    lappend html ""
    lappend html "  <div class=\"grid\">"
    lappend html "    <div>"
    lappend html "      <div class=\"player\" id=\"player\">"
    lappend html "        <div class=\"placeholder\" id=\"placeholder\">"
    lappend html "          <div style=\"font-size:34px\">&#x1F4FA;</div>"
    lappend html "          <div id=\"phText\">Konto eingeben und &#8222;Anzeigen&#8220; dr&#252;cken.</div>"
    lappend html "        </div>"
    lappend html "      </div>"
    lappend html "      <p class=\"note\">"
    lappend html "        Eingebettet wird der offizielle TikTok-Live-Player"
    lappend html "        (<code>tiktok.com/embed/live/@name</code>). Er ist auf reines Zuschauen"
    lappend html "        ausgelegt: <b>keine Anmeldung, keine Geschenk- oder Kauf-Oberfl&#228;che</b>."
    lappend html "        Damit entfallen die kostenpflichtigen Aktionen, die im normalen Frontend"
    lappend html "        erreichbar w&#228;ren &#8212; brauchbar f&#252;r Mitschauen ohne Konto und ohne Kaufrisiko."
    lappend html "      </p>"
    lappend html "    </div>"
    lappend html ""
    lappend html "    <div>"
    lappend html "      <div class=\"card\">"
    lappend html "        <h2>Status</h2>"
    lappend html "        <div id=\"status\" class=\"meta\">&#8212;</div>"
    lappend html "      </div>"
    lappend html "      <div class=\"card\" style=\"margin-top:12px\">"
    lappend html "        <h2>Letzte Sendungen</h2>"
    lappend html "        <div id=\"streams\" class=\"meta\">&#8212;</div>"
    lappend html "      </div>"
    lappend html "      <div class=\"card\" style=\"margin-top:12px\">"
    lappend html "        <h2>Datenquelle</h2>"
    lappend html "        <div class=\"meta\" id=\"source\">"
    lappend html "          Statusdaten &#252;ber den lokalen Monitor"
    lappend html "          (<code>/api/tiktok/status</code>) oder direkt von der &#246;ffentlichen"
    lappend html "          Profilseite eines Aufzeichnungsdienstes. Kein Konto, keine Umgehung"
    lappend html "          von Zugangskontrollen."
    lappend html "        </div>"
    lappend html "      </div>"
    lappend html "    </div>"
    lappend html "  </div>"
    lappend html "</div>"
    lappend html ""
    lappend html "<script src=\"./tiktok-companion.js\"></script>"
    lappend html "<script>"
    lappend html "  // Standalone-Betrieb: Parameter aus der URL (?user=creator&api=http://127.0.0.1:8765)"
    lappend html "  const params = new URLSearchParams(location.search);"
    lappend html "  window.TTC = new TikTokCompanion({"
    lappend html "    apiBase: params.get('api') || 'http://127.0.0.1:8765',"
    lappend html "    onState: renderState,"
    lappend html "    onError: msg => {"
    lappend html "      const box = document.getElementById('error');"
    lappend html "      if(!msg){ box.innerHTML = ''; return; }"
    lappend html "      const local = location.protocol === 'file:';"
    lappend html "      box.innerHTML = '<div class=\"err\"><b>Status nicht abrufbar.</b><br>' + esc(msg) +"
    lappend html "        '<br><br>Der Browser l&#228;sst aus dieser Seite heraus keinen direkten Abruf ' +"
    lappend html "        'fremder Server zu' + (local ? ' (lokale Datei, Herkunft &#8222;null&#8220;)' : '') + '. Zwei Wege:' +"
    lappend html "        '<br>&#8226; <b>Monitor starten</b> &#8212; im Projektordner <code>python server.py</code>, ' +"
    lappend html "        'dann hier neu laden. Er liefert den Status und erlaubt den Zugriff ausdr&#252;cklich.' +"
    lappend html "        '<br>&#8226; <b>Als Erweiterung laden</b> &#8212; mit <code>host_permissions</code> f&#252;r ' +"
    lappend html "        '<code>streamrecorder.io</code>, siehe plugin/README.md.' +"
    lappend html "        '<br><br>Der Player unten funktioniert unabh&#228;ngig davon: &#8222;Player trotzdem laden&#8220;.</div>';"
    lappend html "    }"
    lappend html "  });"
    lappend html ""
    lappend html "  const \\$ = s => document.querySelector(s);"
    lappend html "  const esc = s => String(s ?? '').replace(/[&<>\"\\]/g, c =>"
    lappend html "    ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));"
    lappend html ""
    lappend html "  function renderState(st){"
    lappend html "    const live = st.live === true;"
    lappend html "    \\$('#badge').className = 'badge' + (live ? ' live' : '');"
    lappend html "    \\$('#badgeText').textContent = live ? 'LIVE' : (st.live === false ? 'offline' : 'unbekannt');"
    lappend html "    \\$('#checked').textContent = st.checked_at"
    lappend html "      ? 'gepr&#252;ft ' + new Date(st.checked_at).toLocaleTimeString('de-DE') : '';"
    lappend html ""
    lappend html "    \\$('#status').innerHTML ="
    lappend html "      (st.title ? '<div style=\"color:var(--text);font-weight:600\">' + esc(st.title) + '</div>' : '') +"
    lappend html "      (st.started_at ? '<div>Beginn ' + esc(st.started_at.replace('T', ' ')) +"
    lappend html "        (st.since ? ' &#183; seit ca. ' + esc(st.since) : '') + '</div>' : '') +"
    lappend html "      (st.last_seen ? '<div>zuletzt gesehen ' + esc(st.last_seen) + '</div>' : '') +"
    lappend html "      (st.streams_total ? '<div>' + st.streams_total + ' Sendungen &#183; ' +"
    lappend html "        esc(st.airtime || '') + ' Sendezeit &#183; ' + (st.active_days || '?') + ' aktive Tage</div>' : '') +"
    lappend html "      '<div style=\"margin-top:8px\"><a href=\"' + esc(st.profile_url || '#') +"
    lappend html "        '\" target=\"_blank\" rel=\"noopener\">Profil</a> &#183; <a href=\"' +"
    lappend html "        esc(st.live_url || '#') + '\" target=\"_blank\" rel=\"noopener\">Live-Seite</a></div>';"
    lappend html ""
    lappend html "    \\$('#streams').innerHTML = (st.streams || []).length"
    lappend html "      ? st.streams.slice(0, 10).map(s =>"
    lappend html "          '<div class=\"stream' + (s.is_live ? ' now' : '') + '\">' +"
    lappend html "          '<span class=\"when\">' + esc(s.day.slice(5)) + ' ' + esc(s.time || '') + '</span>' +"
    lappend html "          '<span class=\"t\">' + esc(s.title || '(ohne Titel)') + '</span>' +"
    lappend html "          '<span class=\"when\">' + esc(s.duration || '') + '</span></div>').join('')"
    lappend html "      : 'keine Daten';"
    lappend html ""
    lappend html "    const wantPlayer = live && \\$('#autoplay').checked;"
    lappend html "    const holder = \\$('#player');"
    lappend html "    if(wantPlayer && !holder.querySelector('iframe')){"
    lappend html "      const f = document.createElement('iframe');"
    lappend html "      f.src = st.embed_url;"
    lappend html "      f.allow = 'autoplay; encrypted-media; picture-in-picture';"
    lappend html "      f.referrerPolicy = 'origin';"
    lappend html "      f.title = 'TikTok Live von @' + st.username;"
    lappend html "      holder.appendChild(f);"
    lappend html "      \\$('#placeholder').style.display = 'none';"
    lappend html "    } else if(!live){"
    lappend html "      holder.querySelectorAll('iframe').forEach(f => f.remove());"
    lappend html "      \\$('#placeholder').style.display = '';"
    lappend html "      \\$('#phText').textContent = st.username"
    lappend html "        ? '@' + st.username + ' ist gerade offline.'"
    lappend html "        : 'Konto eingeben und &#8222;Anzeigen&#8220; dr&#252;cken.';"
    lappend html "    }"
    lappend html "  }"
    lappend html ""
    lappend html "  \\$('#go').onclick = () => {"
    lappend html "    const u = \\$('#user').value.trim().replace(/^@/, '');"
    lappend html "    if(!u) return;"
    lappend html "    document.querySelectorAll('#player iframe').forEach(f => f.remove());"
    lappend html "    localStorage.setItem('ttc.user', u);"
    lappend html "    window.TTC.watch(u, parseInt(\\$('#every').value, 10));"
    lappend html "  };"
    lappend html "  \\$('#user').addEventListener('keydown', e => { if(e.key === 'Enter') \\$('#go').click(); });"
    lappend html "  \\$('#force').onclick = () => {"
    lappend html "    const u = \\$('#user').value.trim().replace(/^@/, '');"
    lappend html "    if(!u) return;"
    lappend html "    const holder = \\$('#player');"
    lappend html "    holder.querySelectorAll('iframe').forEach(f => f.remove());"
    lappend html "    const f = document.createElement('iframe');"
    lappend html "    f.src = TikTokCompanion.embedUrl(u);"
    lappend html "    f.allow = 'autoplay; encrypted-media; picture-in-picture';"
    lappend html "    f.referrerPolicy = 'origin';"
    lappend html "    f.title = 'TikTok Live von @' + u;"
    lappend html "    holder.appendChild(f);"
    lappend html "    \\$('#placeholder').style.display = 'none';"
    lappend html "  };"
    lappend html "  \\$('#every').addEventListener('change', () => \\$('#go').click());"
    lappend html "  \\$('#notify').addEventListener('change', async e => {"
    lappend html "    window.TTC.notifyOnLive = e.target.checked;"
    lappend html "    if(e.target.checked && 'Notification' in window && Notification.permission === 'default'){"
    lappend html "      await Notification.requestPermission();"
    lappend html "    }"
    lappend html "  });"
    lappend html ""
    lappend html "  const saved = params.get('user') || localStorage.getItem('ttc.user');"
    lappend html "  if(saved){ \\$('#user').value = saved; \\$('#go').click(); }"
    lappend html "</script>"
    lappend html "</body>"
    lappend html "</html>"
    
    return [join $html "\n"]
}

# Main execution
if {$argc != 1} {
    puts stderr "Usage: $argv0 <output-file>"
    exit 1
}

set output_file [lindex $argv 0]
set html_content [generate_html]

if {[catch {open $output_file w} file_handle]} {
    puts stderr "Error: Could not open file '$output_file' for writing"
    exit 1
}

puts $file_handle $html_content
close $file_handle

puts "HTML file generated successfully: $output_file"
