#!/usr/bin/env tclsh8.6
# 1781743218784.html — portiert nach tcl
# Quelle: html, Projects@secret-vault-public:secret-vault-public/versions/1781743218784.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# Tcl port of Secret-Vault Public HTML application
# Generates the complete HTML document dynamically

proc generate_html {output_file} {
    set html {}
    
    # Add DOCTYPE and opening script tag
    append html "<!DOCTYPE html>\n"
    append html "<script type=\"application/json\" id=\"cowork-artifact-meta\">\n"
    append html "{\n"
    append html "  \"name\": \"Secret Vault Public\",\n"
    append html "  \"schemaVersion\": 1,\n"
    append html "  \"description\": \"Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet.\",\n"
    append html "  \"mcpTools\": [],\n"
    append html "  \"mcpServerNames\": []\n"
    append html "}\n"
    append html "</script>\n"
    
    # Add html tag with language
    append html "<html lang=\"de\">\n"
    
    # Add head section
    append html "<head>\n"
    append html "<meta charset=\"utf-8\">\n"
    append html "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    append html "<title>Secret-Vault Public</title>\n"
    append html "<style>\n"
    append html ":root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}\n"
    append html "*{box-sizing:border-box;}\n"
    append html "body{margin:0;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}\n"
    append html ".wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}\n"
    append html ".brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}\n"
    append html ".mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}\n"
    append html ".mark:after{content:\"\";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}\n"
    append html "h1{font-size:21px;margin:0;font-weight:700;}\n"
    append html ".sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}\n"
    append html ".card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}\n"
    append html ".card h2{font-size:14px;margin:0 0 10px;}\n"
    append html "label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}\n"
    append html "input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}\n"
    append html "textarea{min-height:90px;white-space:pre;overflow:auto;}\n"
    append html ".row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}\n"
    append html ".btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}\n"
    append html ".btn:hover{transform:translateY(-1px);}\n"
    append html ".btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}\n"
    append html ".btn.sm{padding:5px 9px;font-size:12px;}\n"
    append html ".msg{font-size:12px;margin-left:6px;}\n"
    append html ".msg.ok{color:var(--ok);} .msg.err{color:var(--err);}\n"
    append html ".prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}\n"
    append html ".prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}\n"
    append html ".kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}\n"
    append html ".kv input{font-size:12px;padding:5px 7px;}\n"
    append html ".kv .k{color:var(--muted);font-weight:600;}\n"
    append html ".muted{color:var(--faint);font-size:13px;}\n"
    append html ".hide{display:none;}\n"
    append html ".foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}\n"
    append html "a{color:var(--accent);}\n"
    append html "</style>\n"
    append html "</head>\n"
    
    # Add body section
    append html "<body>\n"
    append html "<div class=\"wrap\">\n"
    append html "  <div class=\"brand\"><div class=\"mark\"></div><h1 id=\"title\">Secret-Vault Public</h1></div>\n"
    append html "  <div class=\"sub\" id=\"sub\">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>\n"
    append html "\n"
    append html "  <div class=\"card\">\n"
    append html "    <h2 id=\"h-open\">Öffnen oder neu</h2>\n"
    append html "    <label class=\"lab\" id=\"l-pass\">Passphrase</label>\n"
    append html "    <input id=\"pass\" type=\"password\" placeholder=\"Passphrase…\">\n"
    append html "    <label class=\"lab\" id=\"l-file\">Vault laden (Datei oder Base64 einfügen)</label>\n"
    append html "    <input id=\"file\" type=\"file\" accept=\".svpb,.txt,.vault,.b64\">\n"
    append html "    <textarea id=\"blob\" placeholder=\"…oder Base64 hier einfügen\"></textarea>\n"
    append html "    <div class=\"row\" style=\"margin-top:10px\">\n"
    append html "      <button class=\"btn primary\" id=\"openBtn\">Öffnen / Entschlüsseln</button>\n"
    append html "      <button class=\"btn\" id=\"newBtn\">Neuer leerer Vault</button>\n"
    append html "      <span class=\"msg\" id=\"openMsg\"></span>\n"
    append html "    </div>\n"
    append html "  </div>\n"
    append html "\n"
    append html "  <div class=\"card hide\" id=\"editor\">\n"
    append html "    <h2 id=\"h-edit\">Inhalt</h2>\n"
    append html "    <div id=\"provs\"></div>\n"
    append html "    <div class=\"row\" style=\"margin-top:8px\">\n"
    append html "      <input id=\"newProv\" placeholder=\"Neuer Anbieter (Name)\" style=\"max-width:280px\">\n"
    append html "      <button class=\"btn sm\" id=\"addProvBtn\">+ Anbieter</button>\n"
    append html "    </div>\n"
    append html "  </div>\n"
    append html "\n"
    append html "  <div class=\"card hide\" id=\"out\">\n"
    append html "    <h2 id=\"h-save\">Speichern / Export</h2>\n"
    append html "    <div class=\"row\">\n"
    append html "      <button class=\"btn primary\" id=\"encBtn\">Verschlüsseln</button>\n"
    append html "      <button class=\"btn\" id=\"dlBtn\">Als .svpb herunterladen</button>\n"
    append html "      <button class=\"btn\" id=\"expBtn\">Klartext-JSON exportieren</button>\n"
    append html "      <span class=\"msg\" id=\"saveMsg\"></span>\n"
    append html "    </div>\n"
    append html "    <label class=\"lab\" id=\"l-result\">Ergebnis (zum Kopieren/Speichern)</label>\n"
    append html "    <textarea id=\"result\" readonly></textarea>\n"
    append html "  </div>\n"
    append html "\n"
    append html "  <div class=\"foot\" id=\"foot\"></div>\n"
    append html "</div>\n"
    
    # Add script section
    append html "\n"
    append html "<script>\n"
    append html "const L = ((navigator.language||\"en\").toLowerCase().startsWith(\"de\"))?\"de\":\"en\";\n"
    append html "const T = {\n"
    append html " title:{de:\"Secret-Vault Public\",en:\"Secret-Vault Public\"},\n"
    append html " sub:{de:\"Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.\",en:\"Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server.\"},\n"
    append html " hOpen:{de:\"Öffnen oder neu\",en:\"Open or new\"},\n"
    append html " pass:{de:\"Passphrase\",en:\"Passphrase\"},\n"
    append html " file:{de:\"Vault laden (Datei oder Base64 einfügen)\",en:\"Load vault (file or paste Base64)\"},\n"
    append html " blob:{de:\"…oder Base64 hier einfügen\",en:\"…or paste Base64 here\"},\n"
    append html " open:{de:\"Öffnen / Entschlüsseln\",en:\"Open / Decrypt\"},\n"
    append html " neu:{de:\"Neuer leerer Vault\",en:\"New empty vault\"},\n"
    append html " hEdit:{de:\"Inhalt\",en:\"Content\"},\n"
    append html " newProv:{de:\"Neuer Anbieter (Name)\",en:\"New provider (name)\"},\n"
    append html " addProv:{de:\"+ Anbieter\",en:\"+ Provider\"},\n"
    append html " hSave:{de:\"Speichern / Export\",en:\"Save / Export\"},\n"
    append html " enc:{de:\"Verschlüsseln\",en:\"Encrypt\"},\n"
    append html " dl:{de:\"Als .svpb herunterladen\",en:\"Download as .svpb\"},\n"
    append html " exp:{de:\"Klartext-JSON exportieren\",en:\"Export plaintext JSON\"},\n"
    append html " result:{de:\"Ergebnis (zum Kopieren/Speichern)\",en:\"Result (to copy/save)\"},\n"
    append html " foot:{de:\"Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar.\",en:\"Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it.\"},\n"
    append html " needPass:{de:\"Passphrase eingeben.\",en:\"Enter a passphrase.\"},\n"
    append html " noInput:{de:\"Datei laden oder Base64 einfügen.\",en:\"Load a file or paste Base64.\"},\n"
    append html " bad:{de:\"Falsche Passphrase oder ungültiger Vault.\",en:\"Wrong passphrase or invalid vault.\"},\n"
    append html " opened:{de:\"Geöffnet.\",en:\"Opened.\"},\n"
    append html " created:{de:\"Neuer Vault angelegt.\",en:\"New vault created.\"},\n"
    append html " encrypted:{de:\"Verschlüsselt — unten kopieren oder herunterladen.\",en:\"Encrypted — copy below or download.\"},\n"
    append html " needOpen:{de:\"Erst öffnen/anlegen.\",en:\"Open/create first.\"},\n"
    append html " field:{de:\"Feld\",en:\"field\"}, value:{de:\"Wert\",en:\"value\"},\n"
    append html " addField:{de:\"+ Feld\",en:\"+ field\"}, del:{de:\"✕\",en:\"✕\"},\n"
    append html " newField:{de:\"neues Feld\",en:\"new field\"}, newValue:{de:\"Wert\",en:\"value\"}\n"
    append html "};\n"
    append html "const tr=k=>T[k][L];\n"
    append html "// apply static i18n\n"
    append html "title.textContent=tr(\"title\"); sub.textContent=tr(\"sub\"); document.title=tr(\"title\");\n"
    append html "document.getElementById(\"h-open\").textContent=tr(\"hOpen\");\n"
    append html "document.getElementById(\"l-pass\").textContent=tr(\"pass\");\n"
    append html "document.getElementById(\"l-file\").textContent=tr(\"file\");\n"
    append html "blob.placeholder=tr(\"blob\");\n"
    append html "openBtn.textContent=tr(\"open\"); newBtn.textContent=tr(\"neu\");\n"
    append html "document.getElementById(\"h-edit\").textContent=tr(\"hEdit\");\n"
    append html "newProv.placeholder=tr(\"newProv\"); addProvBtn.textContent=tr(\"addProv\");\n"
    append html "document.getElementById(\"h-save\").textContent=tr(\"hSave\");\n"
    append html "encBtn.textContent=tr(\"enc\"); dlBtn.textContent=tr(\"dl\"); expBtn.textContent=tr(\"exp\");\n"
    append html "document.getElementById(\"l-result\").textContent=tr(\"result\");\n"
    append html "foot.textContent=tr(\"foot\");\n"
    append html "\n"
    append html "let VAULT=null; // {meta, providers:{}}\n"
    append html "\n"
    append html "const enc=new TextEncoder(), dec=new TextDecoder();\n"
    append html "function u8b64(u8){ let s=\"\"; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }\n"
    append html "function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }\n"
    append html "async function deriveKey(pw,salt){\n"
    append html "  const km=await crypto.subtle.importKey(\"raw\",enc.encode(pw),\"PBKDF2\",false,[\"deriveKey\"]);\n"
    append html "  return crypto.subtle.deriveKey({name:\"PBKDF2\",salt,iterations:210000,hash:\"SHA-256\"},km,{name:\"AES-GCM\",length:256},false,[\"encrypt\",\"decrypt\"]);\n"
    append html "}\n"
    append html "async function encryptObj(obj,pw){\n"
    append html "  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));\n"
    append html "  const key=await deriveKey(pw,salt);\n"
    append html "  const ct=new Uint8Array(await crypto.subtle.encrypt({name:\"AES-GCM\",iv},key,enc.encode(JSON.stringify(obj,null,2))));\n"
    append html "  const magic=enc.encode(\"SVPB1\"); const out=new Uint8Array(5+16+12+ct.length);\n"
    append html "  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);\n"
    append html "}\n"
    append html "async function decryptB64(b64,pw){\n"
    append html "  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!==\"SVPB1\") throw new Error(\"magic\");\n"
    append html "  const key=await deriveKey(pw,raw.slice(5,21));\n"
    append html "  const pt=await crypto.subtle.decrypt({name:\"AES-GCM\",iv:raw.slice(21,33)},key,raw.slice(33));\n"
    append html "  return JSON.parse(dec.decode(pt));\n"
    append html "}\n"
    append html "function esc(s){return (s==null?\"\":String(s)).replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;'}[c]));}\n"
    append html "\n"
    append html "function renderEditor(){\n"
    append html "  document.getElementById(\"editor\").classList.remove(\"hide\");\n"
    append html "  document.getElementById(\"out\").classList.remove(\"hide\");\n"
    append html "  const P=VAULT.providers||{}; const root=document.getElementById(\"provs\"); root.innerHTML=\"\";\n"
    append html "  Object.keys(P).forEach(name=>{\n"
    append html "    const d=document.createElement(\"div\"); d.className=\"prov\";\n"
    append html "    let rows=\"\";\n"
    append html "    Object.keys(P[name]).forEach(k=>{ rows+=`<div class=\"kv\"><span class=\"k\">\${esc(k)}</span><input data-p=\"\${esc(name)}\" data-k=\"\${esc(k)}\" value=\"\${esc(P[name][k])}\"><button class=\"btn sm\" data-del=\"\${esc(name)}|\${esc(k)}\">\${tr(\"del\")}</button></div>`; });\n"
    append html "    d.innerHTML=`<h3>\${esc(name)} <button class=\"btn sm\" data-delp=\"\${esc(name)}\">\${tr(\"del\")}</button></h3>\${rows}\n"
    append html "      <div class=\"row\" style=\"margin-top:6px\"><input class=\"nf\" data-np=\"\${esc(name)}\" placeholder=\"\${tr(\"newField\")}\" style=\"max-width:180px\"><input class=\"nv\" data-np=\"\${esc(name)}\" placeholder=\"\${tr(\"newValue\")}\" style=\"max-width:260px\"><button class=\"btn sm\" data-addf=\"\${esc(name)}\">\${tr(\"addField\")}</button></div>`;\n"
    append html "    root.appendChild(d);\n"
    append html "  });\n"
    append html "  root.querySelectorAll(\"input[data-k]\").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });\n"
    append html "  root.querySelectorAll(\"button[data-del]\").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split(\"|\"); delete VAULT.providers[p][k]; renderEditor(); });\n"
    append html "  root.querySelectorAll(\"button[data-delp]\").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });\n"
    append html "  root.querySelectorAll(\"button[data-addf]\").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np=\"\${CSS.escape(p)}\"]`).value.trim(); const nv=root.querySelector(`.nv[data-np=\"\${CSS.escape(p)}\"]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });\n"
    append html "}\n"
    append html "\n"
    append html "document.getElementById(\"file\").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };\n"
    append html "openBtn.onclick=async()=>{\n"
    append html "  const m=document.getElementById(\"openMsg\"); m.className=\"msg\"; m.textContent=\"\";\n"
    append html "  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }\n"
    append html "  if(!blob.value.trim()){ m.className=\"msg err\"; m.textContent=tr(\"noInput\"); return; }\n"
    append html "  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className=\"msg ok\"; m.textContent=tr(\"opened\"); }\n"
    append html "  catch(err){ m.className=\"msg err\"; m.textContent=tr(\"bad\"); }\n"
    append html "};\n"
    append html "newBtn.onclick=()=>{\n"
    append html "  const m=document.getElementById(\"openMsg\");\n"
    append html "  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }\n"
    append html "  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:\"SVPB1\"},providers:{}}; renderEditor();\n"
    append html "  m.className=\"msg ok\"; m.textContent=tr(\"created\");\n"
    append html "};\n"
    append html "addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=\"\"; renderEditor(); } };\n"
    append html "encBtn.onclick=async()=>{\n"
    append html "  const m=document.getElementById(\"saveMsg\"); m.className=\"msg\";\n"
    append html "  if(!VAULT){ m.className=\"msg err\"; m.textContent=tr(\"needOpen\"); return; }\n"
    append html "  if(!pass.value){ m.className=\"msg err\"; m.textContent=tr(\"needPass\"); return; }\n"
    append html "  result.value=await encryptObj(VAULT,pass.value); m.className=\"msg ok\"; m.textContent=tr(\"encrypted\");\n"
    append html "};\n"
    append html "dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:\"text/plain\"}); const u=URL.createObjectURL(b); const a=document.createElement(\"a\"); a.href=u; a.download=\"vault.svpb\"; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };\n"
    append html "expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };\n"
    append html "</script>\n"
    append html "</body>\n"
    append html "</html>\n"
    
    # Write to file
    set fh [open $output_file w]
    puts -nonewline $fh $html
    close $fh
}

# Main execution
if {$argc != 1} {
    puts "Usage: $argv0 <output_file>"
    exit 1
}

generate_html [lindex $argv 0]
