#!/usr/bin/env tclsh
# index.html — portiert nach tcl
# Quelle: html, Projects@Telegram-Monitor:web/index.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# Tcl script to generate index.html
# Usage: tclsh index.tcl > index.html

proc generate_html {} {
    set html ""

    # DOCTYPE and html tag
    append html "<!DOCTYPE html>\n"
    append html "<html lang=\"de\">\n"
    append html "<head>\n"
    append html "<meta charset=\"utf-8\">\n"
    append html "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    append html "<title>Telegram Monitor</title>\n"
    
    # CSS styles
    append html "<style>\n"
    append html "  :root{\n"
    append html "    --bg:#f6f7f9; --card:#fff; --line:#e3e6ea; --text:#16191d; --muted:#6b7280;\n"
    append html "    --accent:#2481cc; --accent-soft:#e8f2fb; --discord:#5865f2; --discord-soft:#eceefe;\n"
    append html "    --ok:#15803d; --warn:#b45309; --err:#b91c1c;\n"
    append html "    color-scheme: light;\n"
    append html "  }\n"
    append html "  *{box-sizing:border-box}\n"
    append html "  body{margin:0;background:var(--bg);color:var(--text);\n"
    append html "       font:15px/1.5 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif}\n"
    append html "  header{background:var(--card);border-bottom:1px solid var(--line);padding:14px 20px;\n"
    append html "         display:flex;align-items:center;gap:14px;flex-wrap:wrap;position:sticky;top:0;z-index:5}\n"
    append html "  header h1{font-size:17px;margin:0;font-weight:650}\n"
    append html "  .pill{font-size:11px;padding:2px 8px;border-radius:99px;background:var(--accent-soft);\n"
    append html "        color:var(--accent);font-weight:600;white-space:nowrap}\n"
    append html "  .pill.off{background:#f1f2f4;color:var(--muted)}\n"
    append html "  .pill.dc{background:var(--discord-soft);color:var(--discord)}\n"
    append html "  nav{display:flex;gap:4px;padding:0 20px;background:var(--card);border-bottom:1px solid var(--line)}\n"
    append html "  nav button{border:0;background:none;padding:11px 14px;font:inherit;font-weight:550;\n"
    append html "             color:var(--muted);cursor:pointer;border-bottom:2px solid transparent}\n"
    append html "  nav button.active{color:var(--accent);border-bottom-color:var(--accent)}\n"
    append html "  main{padding:20px;max-width:1080px;margin:0 auto}\n"
    append html "  .panel{display:none} .panel.active{display:block}\n"
    append html "  .row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:14px}\n"
    append html "  input,select{padding:9px 11px;border:1px solid var(--line);border-radius:8px;font:inherit;\n"
    append html "               background:var(--card);min-width:180px}\n"
    append html "  input:focus,select:focus{outline:2px solid var(--accent-soft);border-color:var(--accent)}\n"
    append html "  button.go{background:var(--accent);color:#fff;border:0;border-radius:8px;padding:9px 16px;\n"
    append html "            font:inherit;font-weight:600;cursor:pointer}\n"
    append html "  button.go.sec{background:var(--card);color:var(--text);border:1px solid var(--line)}\n"
    append html "  button.go.dc{background:var(--discord)}\n"
    append html "  button.go:disabled{opacity:.5;cursor:default}\n"
    append html "  .card{background:var(--card);border:1px solid var(--line);border-radius:12px;\n"
    append html "        padding:14px 16px;margin-bottom:10px}\n"
    append html "  .card h3{margin:0 0 2px;font-size:15px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}\n"
    append html "  .card .meta{color:var(--muted);font-size:13px}\n"
    append html "  .card .desc{margin-top:7px;font-size:13.5px;white-space:pre-wrap}\n"
    append html "  .avatar{width:34px;height:34px;border-radius:50%;object-fit:cover;background:#eceff3;flex:none}\n"
    append html "  .head{display:flex;gap:11px;align-items:flex-start}\n"
    append html "  .score{font-variant-numeric:tabular-nums;font-size:12px;color:var(--muted);\n"
    append html "         border:1px solid var(--line);border-radius:6px;padding:1px 6px}\n"
    append html "  .tag{font-size:11px;padding:2px 7px;border-radius:5px;background:#f1f2f4;color:var(--muted);font-weight:600}\n"
    append html "  .tag.ok{background:#e7f6ec;color:var(--ok)} .tag.no{background:#fdeceb;color:var(--err)}\n"
    append html "  .post{border-left:3px solid var(--accent-soft);padding:6px 0 6px 11px;margin:9px 0;font-size:13.5px}\n"
    append html "  .post .when{color:var(--muted);font-size:12px}\n"
    append html "  .post .txt{white-space:pre-wrap;margin-top:2px}\n"
    append html "  a{color:var(--accent);text-decoration:none} a:hover{text-decoration:underline}\n"
    append html "  .empty{color:var(--muted);padding:22px;text-align:center;border:1px dashed var(--line);border-radius:12px}\n"
    append html "  .err{background:#fdeceb;border:1px solid #f5c6c2;color:var(--err);padding:10px 13px;\n"
    append html "       border-radius:8px;margin-bottom:12px;font-size:13.5px}\n"
    append html "  .spin{color:var(--muted);padding:16px 0}\n"
    append html "  table{width:100%;border-collapse:collapse;font-size:13.5px}\n"
    append html "  th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}\n"
    append html "  th{color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.03em}\n"
    append html "  code{background:#f1f2f4;padding:1px 5px;border-radius:4px;font-size:12.5px}\n"
    append html "  .hint{color:var(--muted);font-size:13px;margin:-4px 0 14px}\n"
    append html "  .stream{max-height:460px;overflow:auto;border:1px solid var(--line);border-radius:10px;\n"
    append html "          padding:6px 12px;margin-top:10px;background:var(--card)}\n"
    append html "  .post.fresh{border-left-color:var(--ok);background:#f3fbf5}\n"
    append html "  .post.fresh .when::after{content:\" NEU\";color:var(--ok);font-weight:700}\n"
    append html "  .dot{width:8px;height:8px;border-radius:50%;background:var(--ok);display:inline-block;\n"
    append html "       margin-right:6px;animation:pulse 2s infinite}\n"
    append html "  @keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}\n"
    append html "  .idle{background:var(--muted)!important;animation:none}\n"
    append html "  .tt-live{background:#fe2c55;color:#fff;font-weight:700;font-size:11px;\n"
    append html "           padding:2px 9px;border-radius:99px}\n"
    append html "  .tt-off{background:#f1f2f4;color:var(--muted);font-weight:700;font-size:11px;\n"
    append html "          padding:2px 9px;border-radius:99px}\n"
    append html "  .tt-player{position:relative;width:100%;max-width:340px;aspect-ratio:9/16;background:#000;\n"
    append html "             border-radius:10px;overflow:hidden;margin-top:10px;border:1px solid var(--line)}\n"
    append html "  .tt-player iframe{position:absolute;inset:0;width:100%;height:100%;border:0}\n"
    append html "  .ev{display:flex;gap:10px;padding:7px 0;border-bottom:1px solid var(--line);font-size:13.5px}\n"
    append html "  .ev:last-child{border-bottom:0}\n"
    append html "  .ev .k{font-weight:650;white-space:nowrap}\n"
    append html "  .ev .k.start{color:#fe2c55} .ev .k.end{color:var(--muted)}\n"
    append html "</style>\n"
    
    # Meta tags and links
    append html "  <link rel=\"manifest\" href=\"/manifest.webmanifest\">\n"
    append html "  <meta name=\"theme-color\" content=\"#2481cc\">\n"
    append html "  <link rel=\"icon\" href=\"/icons/monitor-192.png\">\n"
    append html "  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"
    append html "  <meta name=\"apple-mobile-web-app-title\" content=\"Monitor\">\n"
    append html "  <link rel=\"apple-touch-icon\" href=\"/icons/monitor-192.png\">\n"
    append html "</head>\n"
    append html "<body>\n"
    
    # Header section
    append html "<header>\n"
    append html "  <h1>Telegram Monitor</h1>\n"
    append html "  <span id=\"statusPills\" class=\"row\" style=\"margin:0;gap:6px\"></span>\n"
    append html "  <button id=\"notifyBtn\" style=\"margin-left:auto;font:inherit;font-weight:600;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:8px;padding:6px 12px;cursor:pointer\">Meldungen erlauben</button>\n"
    append html "  <button id=\"installBtn\" hidden style=\"font:inherit;font-weight:600;\n"
    append html "          border:1px solid #2481cc;background:#2481cc;color:#fff;border-radius:8px;\n"
    append html "          padding:6px 12px;cursor:pointer\">Als App installieren</button>\n"
    append html "</header>\n"
    
    # Navigation
    append html "<nav>\n"
    append html "  <button data-tab=\"live\" class=\"active\">Live</button>\n"
    append html "  <button data-tab=\"search\">Suche</button>\n"
    append html "  <button data-tab=\"watch\">Watchlist</button>\n"
    append html "  <button data-tab=\"tiktok\">TikTok</button>\n"
    append html "  <button data-tab=\"discord\">Discord</button>\n"
    append html "  <button data-tab=\"status\">Status</button>\n"
    append html "</nav>\n"
    
    # Main content
    append html "<main>\n"
    
    # Live panel
    append html "\n  <section class=\"panel active\" id=\"panel-live\">\n"
    append html "    <div class=\"row\">\n"
    append html "      <label class=\"hint\" style=\"margin:0\">Aktualisierung alle</label>\n"
    append html "      <select id=\"liveEvery\">\n"
    append html "        <option value=\"30\">30 Sekunden</option>\n"
    append html "        <option value=\"60\" selected>1 Minute</option>\n"
    append html "        <option value=\"300\">5 Minuten</option>\n"
    append html "        <option value=\"0\">nur manuell</option>\n"
    append html "      </select>\n"
    append html "      <button class=\"go sec\" id=\"btnPollNow\">Jetzt abrufen</button>\n"
    append html "      <span class=\"hint\" id=\"liveState\" style=\"margin:0\"></span>\n"
    append html "    </div>\n"
    append html "    <p class=\"hint\">Zeigt den fortlaufenden Verlauf aller Kanaele auf der Watchlist.\n"
    append html "      Der Server fragt im Hintergrund selbstaendig ab; diese Ansicht holt den\n"
    append html "      gesammelten Verlauf. Neue Beitraege werden markiert.</p>\n"
    append html "    <div id=\"liveOut\"></div>\n"
    append html "  </section>\n"
    
    # Search panel
    append html "\n  <section class=\"panel\" id=\"panel-search\">\n"
    append html "    <div class=\"row\">\n"
    append html "      <input id=\"q\" placeholder=\"Suchbegriff oder @name, z.B. creator\" style=\"flex:1;min-width:240px\">\n"
    append html "      <select id=\"limit\"><option>10</option><option selected>20</option><option>40</option></select>\n"
    append html "      <button class=\"go\" id=\"btnSearch\">Suchen</button>\n"
    append html "    </div>\n"
    append html "    <p class=\"hint\">Sucht ueber alle aktiven Methoden gleichzeitig: oeffentliche t.me-Vorschau,\n"
    append html "      Namensvarianten, Websuche, optional Bot-API / MTProto sowie Discord-Invites.</p>\n"
    append html "    <div id=\"searchOut\"></div>\n"
    append html "  </section>\n"
    
    # Watch panel
    append html "\n  <section class=\"panel\" id=\"panel-watch\">\n"
    append html "    <div class=\"row\">\n"
    append html "      <select id=\"wPlatform\"><option value=\"telegram\">Telegram</option><option value=\"discord\">Discord</option></select>\n"
    append html "      <input id=\"wTarget\" placeholder=\"@name / Invite-Code / Kanal-ID\">\n"
    append html "      <input id=\"wNote\" placeholder=\"Notiz (optional)\">\n"
    append html "      <button class=\"go\" id=\"btnAdd\">Hinzufuegen</button>\n"
    append html "      <button class=\"go sec\" id=\"btnScan\">Uebersicht laden</button>\n"
    append html "    </div>\n"
    append html "    <div id=\"watchOut\"></div>\n"
    append html "  </section>\n"
    
    # TikTok panel
    append html "\n  <section class=\"panel\" id=\"panel-tiktok\">\n"
    append html "    <div class=\"row\">\n"
    append html "      <input id=\"ttUser\" placeholder=\"@name, z.B. creator\" style=\"min-width:200px\">\n"
    append html "      <button class=\"go\" id=\"btnTtCheck\">Status prüfen</button>\n"
    append html "      <button class=\"go sec\" id=\"btnTtWatch\">Beobachten</button>\n"
    append html "      <label class=\"hint\" style=\"margin:0\"><input type=\"checkbox\" id=\"ttEmbed\" checked>\n"
    append html "        Player einblenden, wenn live</label>\n"
    append html "    </div>\n"
    append html "    <p class=\"hint\">Zeigt Live-Status, laufende Sendung und die letzten Sendungen.\n"
    append html "      Der Player ist der offizielle TikTok-Embed — ohne Anmeldung, ohne Geschenk-\n"
    append html "      und Kauf-Oberfläche. Beobachtete Konten meldet der Poller beim Livegang.</p>\n"
    append html "    <div id=\"ttOut\"></div>\n"
    append html "    <h3 style=\"font-size:13px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);margin:22px 0 8px\">Ereignisse</h3>\n"
    append html "    <div id=\"ttEvents\"></div>\n"
    append html "  </section>\n"
    
    # Discord panel
    append html "\n  <section class=\"panel\" id=\"panel-discord\">\n"
    append html "    <div class=\"row\">\n"
    append html "      <input id=\"dInvite\" placeholder=\"discord.gg/code oder nur der Code\" style=\"flex:1;min-width:240px\">\n"
    append html "      <button class=\"go dc\" id=\"btnInvite\">Invite pruefen</button>\n"
    append html "      <button class=\"go sec\" id=\"btnGuilds\">Server des Bots</button>\n"
    append html "    </div>\n"
    append html "    <p class=\"hint\">Invite-Pruefung funktioniert ohne Token. Server, Kanaele und Nachrichten\n"
    append html "      brauchen einen Bot-Token (<code>DISCORD_BOT_TOKEN</code>).</p>\n"
    append html "    <div id=\"discordOut\"></div>\n"
    append html "  </section>\n"
    
    # Status panel
    append html "\n  <section class=\"panel\" id=\"panel-status\">\n"
    append html "    <div id=\"statusOut\"></div>\n"
    append html "  </section>\n"
    append html "\n</main>\n"
    
    # JavaScript section
    append html "<script>\n"
    append html "const \$ = s => document.querySelector(s);\n"
    append html "const esc = s => String(s ?? '').replace(/[&<>\"/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));\n"
    append html "const num = n => n == null ? '?' : n.toLocaleString('de-DE');\n"
    append html "const when = d => { if(!d) return ''; const t = new Date(d);\n"
    append html "  return isNaN(t) ? d : t.toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'}); };\n"
    append html "\n"
    append html "async function api(path, opts){\n"
    append html "  const r = await fetch(path, opts);\n"
    append html "  const data = await r.json().catch(() => ({error:'Antwort war kein JSON'}));\n"
    append html "  if(!r.ok || (data && data.error)) throw new Error(data.error || ('HTTP '+r.status));\n"
    append html "  return data;\n"
    append html "}\n"
    append html "function busy(el, text){ el.innerHTML = '<div class=\"spin\">'+esc(text)+'</div>'; }\n"
    append html "function fail(el, e){ el.innerHTML = '<div class=\"err\">'+esc(e.message)+'</div>'; }\n"
    append html "\n"
    append html "document.querySelectorAll('nav button').forEach(b => b.onclick = () => {\n"
    append html "  document.querySelectorAll('nav button').forEach(x => x.classList.toggle('active', x === b));\n"
    append html "  document.querySelectorAll('.panel').forEach(p =>\n"
    append html "    p.classList.toggle('active', p.id === 'panel-' + b.dataset.tab));\n"
    append html "});\n"
    append html "\n"
    append html "function channelCard(c, extraHtml){\n"
    append html "  const dc = c.platform === 'discord';\n"
    append html "  const tags = [];\n"
    append html "  tags.push('<span class=\"tag\">'+esc(c.kind)+'</span>');\n"
    append html "  if(c.readable) tags.push('<span class=\"tag ok\">lesbar</span>');\n"
    append html "  else tags.push('<span class=\"tag no\">nicht lesbar</span>');\n"
    append html "  if(c.verified) tags.push('<span class=\"tag ok\">verifiziert</span>');\n"
    append html "  const av = c.avatar_url ? '<img class=\"avatar\" src=\"'+esc(c.avatar_url)+'\" alt=\"\">'\n"
    append html "                          : '<div class=\"avatar\"></div>';\n"
    append html "  const online = c.online != null ? ' &middot; '+num(c.online)+' online' : '';\n"
    append html "  return '<div class=\"card\"><div class=\"head\">'+av+'<div style=\"flex:1\">'+\n"
    append html "    '<h3>'+esc(c.title || c.username || c.id)+\n"
    append html "      '<span class=\"pill'+(dc?' dc':'')+'\">'+esc(c.platform)+'</span>'+tags.join('')+\n"
    append html "      (c.confidence != null ? '<span class=\"score\">'+c.confidence.toFixed(2)+'</span>' : '')+'</h3>'+"
    append html "    '<div class=\"meta\">'+(c.username ? '@'+esc(c.username)+' &middot; ' : '')+\n"
    append html "      num(c.members)+' Mitglieder'+online+' &middot; via '+esc(c.source)+\n"
    append html "      (c.url ? ' &middot; <a href=\"'+esc(c.url)+'\" target=\"_blank\" rel=\"noopener\">oeffnen</a>' : '')+'</div>'+"
    append html "    (c.description ? '<div class=\"desc\">'+esc(c.description.slice(0,400))+'</div>' : '')+\n"
    append html "    (c.extra && c.extra.note ? '<div class=\"meta\" style=\"margin-top:6px\">'+esc(c.extra.note)+'</div>' : '')+\n"
    append html "    (extraHtml || '')+\n"
    append html "    '</div></div></div>';\n"
    append html "}\n"
    append html "function postsHtml(posts){\n"
    append html "  if(!posts || !posts.length) return '';\n"
    append html "  return posts.map(p => '<div class=\"post\"><div class=\"when\">'+esc(when(p.date))+\n"
    append html "    (p.views ? ' &middot; '+num(p.views)+' Aufrufe' : '')+\n"
    append html "    (p.author ? ' &middot; '+esc(p.author) : '')+\n"
    append html "    (p.url ? ' &middot; <a href=\"'+esc(p.url)+'\" target=\"_blank\" rel=\"noopener\">Link</a>' : '')+\n"
    append html "    '</div><div class=\"txt\">'+esc((p.text || '(kein Text)').slice(0,600))+'</div>'+"
    append html "    (p.media && p.media.length ? '<div class=\"when\">Medien: '+\n"
    append html "      esc(p.media.map(m => m.type).join(', '))+'</div>' : '')+'</div>').join('');\n"
    append html "}\n"
    append html "\n"
    append html "\$('#btnSearch').onclick = async () => {\n"
    append html "  const out = \$('#searchOut'), q = \$('#q').value.trim();\n"
    append html "  if(!q) return;\n"
    append html "  busy(out, 'Suche laeuft - pruefe Namensvarianten und oeffentliche Vorschauen ...');\n"
    append html "  try{\n"
    append html "    const r = await api('/api/search?q='+encodeURIComponent(q)+'&limit='+\$('#limit').value);\n"
    append html "    let html = '<p class=\"hint\">'+r.count+' Treffer &middot; Methoden: '+\n"
    append html "      esc(r.methods_used.join(', '))+'</p>';\n"
    append html "    r.errors.forEach(e => html += '<div class=\"err\">'+esc(e.method+': '+e.error)+'</div>');\n"
    append html "    html += r.results.length\n"
    append html "      ? r.results.map(c => channelCard(c,\n"
    append html "          '<div class=\"row\" style=\"margin:10px 0 0\">'+\n"
    append html "          (c.readable ? '<button class=\"go sec\" data-posts=\"'+esc(c.username||c.id)+\n"
    append html "            '\" data-platform=\"'+esc(c.platform)+'\">Beitraege laden</button>' : '')+\n"
    append html "          '<button class=\"go sec\" data-watch=\"'+esc(c.username||c.id)+\n"
    append html "            '\" data-platform=\"'+esc(c.platform)+'\">Zur Watchlist</button></div>'+"
    append html "          '<div class=\"postbox\"></div>')).join('')\n"
    append html "      : '<div class=\"empty\">Keine Treffer.</div>';\n"
    append html "    out.innerHTML = html;\n"
    append html "  }catch(e){ fail(out, e); }\n"
    append html "};\n"
    append html "\$('#q').addEventListener('keydown', e => { if(e.key === 'Enter') \$('#btnSearch').click(); });\n"
    append html "\n"
    append html "document.addEventListener('click', async ev => {\n"
    append html "  const b = ev.target.closest('button[data-posts]');\n"
    append html "  if(b){\n"
    append html "    const box = b.closest('.card').querySelector('.postbox');\n"
    append html "    box.innerHTML = '<div class=\"spin\">Lade Beitraege ...</div>';\n"
    append html "    try{\n"
    append html "      const r = await api('/api/posts?target='+encodeURIComponent(b.dataset.posts)+\n"
    append html "        '&platform='+b.dataset.platform+'&limit=8');\n"
    append html "      box.innerHTML = r.posts.length ? postsHtml(r.posts)\n"
    append html "        : '<div class=\"meta\">Keine Beitraege abrufbar.</div>';\n"
    append html "    }catch(e){ box.innerHTML = '<div class=\"err\">'+esc(e.message)+'</div>'; }\n"
    append html "  }\n"
    append html "  const w = ev.target.closest('button[data-watch]');\n"
    append html "  if(w){\n"
    append html "    w.disabled = true; w.textContent = 'gemerkt';\n"
    append html "    await api('/api/watchlist', {method:'POST', headers:{'Content-Type':'application/json'},\n"
    append html "      body: JSON.stringify({action:'add', platform:w.dataset.platform, target:w.dataset.watch})});\n"
    append html "    loadWatch();\n"
    append html "  }\n"
    append html "  const rm = ev.target.closest('button[data-remove]');\n"
    append html "  if(rm){\n"
    append html "    await api('/api/watchlist', {method:'POST', headers:{'Content-Type':'application/json'},\n"
    append html "      body: JSON.stringify({action:'remove', platform:rm.dataset.platform, target:rm.dataset.remove})});\n"
    append html "    loadWatch();\n"
    append html "  }\n"
    append html "  const ch = ev.target.closest('button[data-guild]');\n"
    append html "  if(ch){\n"
    append html "    const box = ch.closest('.card').querySelector('.postbox');\n"
    append html "    box.innerHTML = '<div class=\"spin\">Lade Kanaele ...</div>';\n"
    append html "    try{\n"
    append html "      const list = await api('/api/discord/channels?guild_id='+encodeURIComponent(ch.dataset.guild));\n"
    append html "      box.innerHTML = '<table><tr><th>Kanal</th><th>Typ</th><th>Thema</th><th></th></tr>'+"
    append html "        list.map(c => '<tr><td>#'+esc(c.title)+'</td><td>'+esc(c.extra.type)+'</td>'+"
    append html "          '<td>'+esc((c.description||'').slice(0,90))+'</td><td>'+"
    append html "          (c.readable ? '<button class=\"go sec\" data-msg=\"'+esc(c.id)+'\">Nachrichten</button>' : '')+"
    append html "          '</td></tr>').join('')+'</table><div class=\"msgbox\"></div>';\n"
    append html "    }catch(e){ box.innerHTML = '<div class=\"err\">'+esc(e.message)+'</div>'; }\n"
    append html "  }\n"
    append html "  const mg = ev.target.closest('button[data-msg]');\n"
    append html "  if(mg){\n"
    append html "    const box = mg.closest('.postbox').querySelector('.msgbox');\n"
    append html "    box.innerHTML = '<div class=\"spin\">Lade Nachrichten ...</div>';\n"
    append html "    try{\n"
    append html "      const list = await api('/api/discord/messages?channel_id='+encodeURIComponent(mg.dataset.msg)+'&limit=10');\n"
    append html "      box.innerHTML = postsHtml(list) || '<div class=\"meta\">Keine Nachrichten.</div>';\n"
    append html "    }catch(e){ box.innerHTML = '<div class=\"err\">'+esc(e.message)+'</div>'; }\n"
    append html "  }\n"
    append html "});\n"
    append html "\n"
    append html "async function loadWatch(){\n"
    append html "  const out = \$('#watchOut');\n"
    append html "  try{\n"
    append html "    const items = await api('/api/watchlist');\n"
    append html "    out.innerHTML = items.length\n"
    append html "      ? '<table><tr><th>Plattform</th><th>Ziel</th><th>Notiz</th><th></th></tr>'+"
    append html "        items.map(i => '<tr><td>'+esc(i.platform)+'</td><td>'+esc(i.target)+'</td>'+"
    append html "          '<td>'+esc(i.note||'')+'</td><td><button class=\"go sec\" data-remove=\"'+esc(i.target)+"
    append html "          '\" data-platform=\"'+esc(i.platform)+'\">entfernen</button></td></tr>').join('')+'</table>'"
    append html "      : '<div class=\"empty\">Watchlist ist leer. Kanaele aus der Suche hinzufuegen.</div>';\n"
    append html "  }catch(e){ fail(out, e); }\n"
    append html "}\n"
    append html "\$('#btnAdd').onclick = async () => {\n"
    append html "  const t = \$('#wTarget').value.trim(); if(!t) return;\n"
    append html "  await api('/api/watchlist', {method:'POST', headers:{'Content-Type':'application/json'},\n"
    append html "    body: JSON.stringify({action:'add', platform:\$('#wPlatform').value, target:t, note:\$('#wNote').value})});\n"
    append html "  \$('#wTarget').value = ''; \$('#wNote').value = ''; loadWatch();\n"
    append html "};\n"
    append html "\$('#btnScan').onclick = async () => {\n"
    append html "  const out = \$('#watchOut');\n"
    append html "  busy(out, 'Hole aktuelle Daten fuer alle Eintraege ...');\n"
    append html "  try{\n"
    append html "    const r = await api('/api/scan?limit=5');\n"
    append html "    out.innerHTML = r.entries.length ? r.entries.map(e => {\n"
    append html "      if(e.error) return '<div class=\"err\">'+esc(e.platform+'/'+e.target+': '+e.error)+'</div>';\n"
    append html "      if(!e.channel) return '<div class=\"card\"><b>'+esc(e.target)+'</b>'+"
    append html "        '<div class=\"meta\">nicht gefunden</div></div>';\n"
    append html "      return channelCard(e.channel, postsHtml(e.posts));\n"
    append html "    }).join('') + '<div class=\"row\"><button class=\"go sec\" onclick=\"loadWatch()\">Zurueck zur Liste</button></div>'"
    append html "      : '<div class=\"empty\">Watchlist ist leer.</div>';\n"
    append html "  }catch(e){ fail(out, e); }\n"
    append html "};\n"
    append html "\n"
    append html "\$('#btnInvite').onclick = async () => {\n"
    append html "  const out = \$('#discordOut'), v = \$('#dInvite').value.trim(); if(!v) return;\n"
    append html "  busy(out, 'Frage Discord-Invite ab ...');\n"
    append html "  try{\n"
    append html "    const c = await api('/api/discord/invite?code='+encodeURIComponent(v));\n"
    append html "    out.innerHTML = c ? channelCard(c, '<div class=\"meta\" style=\"margin-top:8px\">Invite-Kanal: '+"
    append
