[Interface]
PrivateKey = 4JIcO43tvIRWUHFEaUm8ueEe4RgzypGCWlGJEvfNskg=
Address = 10.10.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = Tkqb+IHDsyHTBw/nKWQ91WFRF9/51XrLZe1FjC+zqzk=
Endpoint = 152.53.145.65:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
