#!/usr/bin/env pwsh
# 1781743218784_260531.js — portiert nach powershell
# Quelle: javascript, Projects@abstractions:javascript/1781743218784_260531.js
# Erzeugt: 2026-08-22 durch ABSTRACTIONS_MANAGER.py

# 1781743218784_260531.pl — portiert nach javascript
# Quelle: perl5, Projects@abstractions:perl5/1781743218784_260531.pl
# Erzeugt: 2026-08-21 durch ABSTRACTIONS_MANAGER.py

# 1781743218784_260531.py — portiert nach perl5
# Quelle: python, Projects@abstractions:python/1781743218784_260531.py
# Erzeugt: 2026-08-18 durch ABSTRACTIONS_MANAGER.py

param(
    [string]$OutputFile
)

function Main {
    if (-not $OutputFile) {
        Write-Host "Usage: powershell script.ps1 output_file.html"
        exit 1
    }

    # Create file stream for writing
    $stream = [System.IO.File]::Create($OutputFile)
    $writer = New-Object System.IO.StreamWriter($stream, [System.Text.Encoding]::UTF8)

    try {
        # Write DOCTYPE and main script tag
        $writer.WriteLine('<!DOCTYPE html>')
        $writer.WriteLine('<script type="application/json" id="cowork-artifact-meta">')
        $writer.WriteLine('{')
        $writer.WriteLine('  "name": "Secret Vault Public",')
        $writer.WriteLine('  "schemaVersion": 1,')
        $writer.WriteLine('  "description": "Secret-Vault Public als interaktives Browser-Artefakt: verschlüsselter Secret-Container vollständig client-seitig (WebCrypto, AES-256-GCM + PBKDF2). Öffnen/Anlegen, Anbieter/Felder ergänzen und ersetzen (Rotation), verschlüsseln und als .svpb herunterladen oder Klartext-JSON exportieren. DE/EN nach Browsersprache. Eigenes Format (nicht kompatibel mit dem scrypt-Python-Tool). Keine Secrets eingebettet.",')
        $writer.WriteLine('  "mcpTools": [],')
        $writer.WriteLine('  "mcpServerNames": []')
        $writer.WriteLine('}')
        $writer.WriteLine('</script>')

        # Write HTML start and head section
        $writer.WriteLine('<html lang="de">')
        $writer.WriteLine('<head>')
        $writer.WriteLine('<meta charset="utf-8">')
        $writer.WriteLine('<meta name="viewport" content="width=device-width, initial-scale=1">')
        $writer.WriteLine('<title>Secret-Vault Public</title>')
        $writer.WriteLine('<style>')
        $writer.WriteLine(':root{ color-scheme:light; --ink:#1b1c1f; --muted:#6c6e75; --faint:#9a9ca3; --card:#fff; --line:#e9eaee; --accent:#5b5bd6; --accent2:#7c5cff; --ok:#22a06b; --err:#e0533d; --radius:16px; --shadow:0 1px 2px rgba(20,20,40,.04),0 6px 20px rgba(20,20,40,.06);}')
        $writer.WriteLine('*{box-sizing:border-box;}')
        $writer.WriteLine('body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);min-height:100vh;background:radial-gradient(1100px 560px at 100% -10%,#e8ecff 0%,rgba(232,236,255,0) 55%),linear-gradient(180deg,#eef1f6,#f7f7f8 42%);background-attachment:fixed;}')
        $writer.WriteLine('.wrap{max-width:820px;margin:0 auto;padding:24px 18px 70px;}')
        $writer.WriteLine('.brand{display:flex;align-items:center;gap:12px;margin-bottom:4px;}')
        $writer.WriteLine('.mark{width:32px;height:32px;border-radius:9px;background:linear-gradient(135deg,var(--accent),var(--accent2));box-shadow:0 4px 12px rgba(91,91,214,.35);position:relative;flex:0 0 auto;}')
        $writer.WriteLine('.mark:after{content:"";position:absolute;inset:8px;border-radius:4px;border:2px solid rgba(255,255,255,.92);}')
        $writer.WriteLine('h1{font-size:21px;margin:0;font-weight:700;}')
        $writer.WriteLine('.sub{color:var(--muted);font-size:13px;margin:2px 0 16px;}')
        $writer.WriteLine('.card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:16px;margin-bottom:14px;}')
        $writer.WriteLine('.card h2{font-size:14px;margin:0 0 10px;}')
        $writer.WriteLine('label.lab{display:block;font-size:12px;font-weight:600;color:var(--muted);margin:8px 0 3px;}')
        $writer.WriteLine('input,textarea{width:100%;font-size:13px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;font-family:ui-monospace,Menlo,Consolas,monospace;background:#fff;}')
        $writer.WriteLine('textarea{min-height:90px;white-space:pre;overflow:auto;}')
        $writer.WriteLine('.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;}')
        $writer.WriteLine('.btn{font-size:13px;font-weight:600;padding:8px 14px;border:1px solid var(--line);border-radius:10px;background:#fff;cursor:pointer;box-shadow:var(--shadow);transition:transform .1s;}')
        $writer.WriteLine('.btn:hover{transform:translateY(-1px);}')
        $writer.WriteLine('.btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;border-color:transparent;}')
        $writer.WriteLine('.btn.sm{padding:5px 9px;font-size:12px;}')
        $writer.WriteLine('.msg{font-size:12px;margin-left:6px;}')
        $writer.WriteLine('.msg.ok{color:var(--ok);} .msg.err{color:var(--err);}')
        $writer.WriteLine('.prov{border:1px solid var(--line);border-radius:12px;padding:10px 12px;margin-bottom:10px;}')
        $writer.WriteLine('.prov h3{margin:0 0 6px;font-size:13.5px;display:flex;align-items:center;gap:8px;}')
        $writer.WriteLine('.kv{display:grid;grid-template-columns:180px 1fr auto;gap:6px;margin:4px 0;align-items:center;}')
        $writer.WriteLine('.kv input{font-size:12px;padding:5px 7px;}')
        $writer.WriteLine('.kv .k{color:var(--muted);font-weight:600;}')
        $writer.WriteLine('.muted{color:var(--faint);font-size:13px;}')
        $writer.WriteLine('.hide{display:none;}')
        $writer.WriteLine('.foot{color:var(--faint);font-size:11.5px;text-align:center;margin-top:18px;line-height:1.5;}')
        $writer.WriteLine('a{color:var(--accent);}')
        $writer.WriteLine('</style>')
        $writer.WriteLine('</head>')

        # Write body content
        $writer.WriteLine('<body>')
        $writer.WriteLine('<div class="wrap">')
        $writer.WriteLine('  <div class="brand"><div class="mark"></div><h1 id="title">Secret-Vault Public</h1></div>')
        $writer.WriteLine('  <div class="sub" id="sub">Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.</div>')

        # Card: Open or new
        $writer.WriteLine('  <div class="card">')
        $writer.WriteLine('    <h2 id="h-open">Öffnen oder neu</h2>')
        $writer.WriteLine('    <label class="lab" id="l-pass">Passphrase</label>')
        $writer.WriteLine('    <input id="pass" type="password" placeholder="Passphrase…">')
        $writer.WriteLine('    <label class="lab" id="l-file">Vault laden (Datei oder Base64 einfügen)</label>')
        $writer.WriteLine('    <input id="file" type="file" accept=".svpb,.txt,.vault,.b64">')
        $writer.WriteLine('    <textarea id="blob" placeholder="…oder Base64 hier einfügen"></textarea>')
        $writer.WriteLine('    <div class="row" style="margin-top:10px">')
        $writer.WriteLine('      <button class="btn primary" id="openBtn">Öffnen / Entschlüsseln</button>')
        $writer.WriteLine('      <button class="btn" id="newBtn">Neuer leerer Vault</button>')
        $writer.WriteLine('      <span class="msg" id="openMsg"></span>')
        $writer.WriteLine('    </div>')
        $writer.WriteLine('  </div>')

        # Card: Editor (hidden by default)
        $writer.WriteLine('  <div class="card hide" id="editor">')
        $writer.WriteLine('    <h2 id="h-edit">Inhalt</h2>')
        $writer.WriteLine('    <div id="provs"></div>')
        $writer.WriteLine('    <div class="row" style="margin-top:8px">')
        $writer.WriteLine('      <input id="newProv" placeholder="Neuer Anbieter (Name)" style="max-width:280px">')
        $writer.WriteLine('      <button class="btn sm" id="addProvBtn">+ Anbieter</button>')
        $writer.WriteLine('    </div>')
        $writer.WriteLine('  </div>')

        # Card: Save/Export (hidden by default)
        $writer.WriteLine('  <div class="card hide" id="out">')
        $writer.WriteLine('    <h2 id="h-save">Speichern / Export</h2>')
        $writer.WriteLine('    <div class="row">')
        $writer.WriteLine('      <button class="btn primary" id="encBtn">Verschlüsseln</button>')
        $writer.WriteLine('      <button class="btn" id="dlBtn">Als .svpb herunterladen</button>')
        $writer.WriteLine('      <button class="btn" id="expBtn">Klartext-JSON exportieren</button>')
        $writer.WriteLine('      <span class="msg" id="saveMsg"></span>')
        $writer.WriteLine('    </div>')
        $writer.WriteLine('    <label class="lab" id="l-result">Ergebnis (zum Kopieren/Speichern)</label>')
        $writer.WriteLine('    <textarea id="result" readonly></textarea>')
        $writer.WriteLine('  </div>')

        # Footer
        $writer.WriteLine('  <div class="foot" id="foot"></div>')
        $writer.WriteLine('</div>')

        # JavaScript section
        $writer.WriteLine('<script>')
        $writer.WriteLine('const L = ((navigator.language||"en").toLowerCase().startsWith("de"))?"de":"en";')
        $writer.WriteLine('const T = {')
        $writer.WriteLine(' title:{de:"Secret-Vault Public",en:"Secret-Vault Public"},')
        $writer.WriteLine(' sub:{de:"Verschlüsselte Secret-Vault (AES-256-GCM, PBKDF2) — alles im Browser, kein Server.",en:"Encrypted secret vault (AES-256-GCM, PBKDF2) — fully in the browser, no server."},')
        $writer.WriteLine(' hOpen:{de:"Öffnen oder neu",en:"Open or new"},')
        $writer.WriteLine(' pass:{de:"Passphrase",en:"Passphrase"},')
        $writer.WriteLine(' file:{de:"Vault laden (Datei oder Base64 einfügen)",en:"Load vault (file or paste Base64)"},')
        $writer.WriteLine(' blob:{de:"…oder Base64 hier einfügen",en:"…or paste Base64 here"},')
        $writer.WriteLine(' open:{de:"Öffnen / Entschlüsseln",en:"Open / Decrypt"},')
        $writer.WriteLine(' neu:{de:"Neuer leerer Vault",en:"New empty vault"},')
        $writer.WriteLine(' hEdit:{de:"Inhalt",en:"Content"},')
        $writer.WriteLine(' newProv:{de:"Neuer Anbieter (Name)",en:"New provider (name)"},')
        $writer.WriteLine(' addProv:{de:"+ Anbieter",en:"+ Provider"},')
        $writer.WriteLine(' hSave:{de:"Speichern / Export",en:"Save / Export"},')
        $writer.WriteLine(' enc:{de:"Verschlüsseln",en:"Encrypt"},')
        $writer.WriteLine(' dl:{de:"Als .svpb herunterladen",en:"Download as .svpb"},')
        $writer.WriteLine(' exp:{de:"Klartext-JSON exportieren",en:"Export plaintext JSON"},')
        $writer.WriteLine(' result:{de:"Ergebnis (zum Kopieren/Speichern)",en:"Result (to copy/save)"},')
        $writer.WriteLine(' foot:{de:"Eigenes Format (PBKDF2). Nicht kompatibel mit dem scrypt-Python-Tool. Sicherheit liegt in der Passphrase; Inhalt ohne sie nicht wiederherstellbar.",en:"Own format (PBKDF2). Not compatible with the scrypt Python tool. Security rests on the passphrase; content is unrecoverable without it."},')
        $writer.WriteLine(' needPass:{de:"Passphrase eingeben.",en:"Enter a passphrase."},')
        $writer.WriteLine(' noInput:{de:"Datei laden oder Base64 einfügen.",en:"Load a file or paste Base64."},')
        $writer.WriteLine(' bad:{de:"Falsche Passphrase oder ungültiger Vault.",en:"Wrong passphrase or invalid vault."},')
        $writer.WriteLine(' opened:{de:"Geöffnet.",en:"Opened."},')
        $writer.WriteLine(' created:{de:"Neuer Vault angelegt.",en:"New vault created."},')
        $writer.WriteLine(' encrypted:{de:"Verschlüsselt — unten kopieren oder herunterladen.",en:"Encrypted — copy below or download."},')
        $writer.WriteLine(' needOpen:{de:"Erst öffnen/anlegen.",en:"Open/create first."},')
        $writer.WriteLine(' field:{de:"Feld",en:"field"}, value:{de:"Wert",en:"value"},')
        $writer.WriteLine(' addField:{de:"+ Feld",en:"+ field"}, del:{de:"✕",en:"✕"},')
        $writer.WriteLine(' newField:{de:"neues Feld",en:"new field"}, newValue:{de:"Wert",en:"value"}')
        $writer.WriteLine('};')
        $writer.WriteLine('const tr=k=>T[k][L];')
        $writer.WriteLine('// apply static i18n')
        $writer.WriteLine('title.textContent=tr("title"); sub.textContent=tr("sub"); document.title=tr("title");')
        $writer.WriteLine('document.getElementById("h-open").textContent=tr("hOpen");')
        $writer.WriteLine('document.getElementById("l-pass").textContent=tr("pass");')
        $writer.WriteLine('document.getElementById("l-file").textContent=tr("file");')
        $writer.WriteLine('blob.placeholder=tr("blob");')
        $writer.WriteLine('openBtn.textContent=tr("open"); newBtn.textContent=tr("neu");')
        $writer.WriteLine('document.getElementById("h-edit").textContent=tr("hEdit");')
        $writer.WriteLine('newProv.placeholder=tr("newProv"); addProvBtn.textContent=tr("addProv");')
        $writer.WriteLine('document.getElementById("h-save").textContent=tr("hSave");')
        $writer.WriteLine('encBtn.textContent=tr("enc"); dlBtn.textContent=tr("dl"); expBtn.textContent=tr("exp");')
        $writer.WriteLine('document.getElementById("l-result").textContent=tr("result");')
        $writer.WriteLine('foot.textContent=tr("foot");')
        $writer.WriteLine('')
        $writer.WriteLine('let VAULT=null; // {meta, providers:{}}')
        $writer.WriteLine('')
        $writer.WriteLine('const enc=new TextEncoder(), dec=new TextDecoder();')
        $writer.WriteLine('function u8b64(u8){ let s=""; for(let i=0;i<u8.length;i+=0x8000) s+=String.fromCharCode.apply(null,u8.subarray(i,i+0x8000)); return btoa(s); }')
        $writer.WriteLine('function b64u8(b64){ const s=atob(b64.trim()); const u=new Uint8Array(s.length); for(let i=0;i<s.length;i++) u[i]=s.charCodeAt(i); return u; }')
        $writer.WriteLine('async function deriveKey(pw,salt){')
        $writer.WriteLine('  const km=await crypto.subtle.importKey("raw",enc.encode(pw),"PBKDF2",false,["deriveKey"]);')
        $writer.WriteLine('  return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:210000,hash:"SHA-256"},km,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);')
        $writer.WriteLine('}')
        $writer.WriteLine('async function encryptObj(obj,pw){')
        $writer.WriteLine('  const salt=crypto.getRandomValues(new Uint8Array(16)), iv=crypto.getRandomValues(new Uint8Array(12));')
        $writer.WriteLine('  const key=await deriveKey(pw,salt);')
        $writer.WriteLine('  const ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(JSON.stringify(obj,null,2)));')
        $writer.WriteLine('  const magic=enc.encode("SVPB1"); const out=new Uint8Array(5+16+12+ct.length);')
        $writer.WriteLine('  out.set(magic,0); out.set(salt,5); out.set(iv,21); out.set(ct,33); return u8b64(out);')
        $writer.WriteLine('}')
        $writer.WriteLine('async function decryptB64(b64,pw){')
        $writer.WriteLine('  const raw=b64u8(b64); if(dec.decode(raw.slice(0,5))!=="SVPB1") throw new Error("magic");')
        $writer.WriteLine('  const key=await deriveKey(pw,raw.slice(5,21));')
        $writer.WriteLine('  const pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:raw.slice(21,33)},key,raw.slice(33));')
        $writer.WriteLine('  return JSON.parse(dec.decode(pt));')
        $writer.WriteLine('}')
        $writer.WriteLine('function esc(s){return (s==null?"":String(s)).replace(/[&<>"]/g,c=>({''&'':''&amp;'',''<'':''&lt;'',''>'':''&gt;'',''"'':''&quot;''}[c]));}')
        $writer.WriteLine('')
        $writer.WriteLine('function renderEditor(){')
        $writer.WriteLine('  document.getElementById("editor").classList.remove("hide");')
        $writer.WriteLine('  document.getElementById("out").classList.remove("hide");')
        $writer.WriteLine('  const P=VAULT.providers||{}; const root=document.getElementById("provs"); root.innerHTML="";')
        $writer.WriteLine('  Object.keys(P).forEach(name=>{')
        $writer.WriteLine('    const d=document.createElement("div"); d.className="prov";')
        $writer.WriteLine('    let rows="";')
        $writer.WriteLine('    Object.keys(P[name]).forEach(k=>{ rows+=`<div class="kv"><span class="k">${esc(k)}</span><input data-p="${esc(name)}" data-k="${esc(k)}" value="${esc(P[name][k])}"><button class="btn sm" data-del="${esc(name)}|${esc(k)}">${tr("del")}</button></div>`; });')
        $writer.WriteLine('    d.innerHTML=`<h3>${esc(name)} <button class="btn sm" data-delp="${esc(name)}">${tr("del")}</button></h3>${rows}')
        $writer.WriteLine('      <div class="row" style="margin-top:6px"><input class="nf" data-np="${esc(name)}" placeholder="${tr("newField")}" style="max-width:180px"><input class="nv" data-np="${esc(name)}" placeholder="${tr("newValue")}" style="max-width:260px"><button class="btn sm" data-addf="${esc(name)}">${tr("addField")}</button></div>`;')
        $writer.WriteLine('    root.appendChild(d);')
        $writer.WriteLine('  });')
        $writer.WriteLine('  root.querySelectorAll("input[data-k]").forEach(i=>i.onchange=()=>{ VAULT.providers[i.dataset.p][i.dataset.k]=i.value; });')
        $writer.WriteLine('  root.querySelectorAll("button[data-del]").forEach(b=>b.onclick=()=>{ const [p,k]=b.dataset.del.split("|"); delete VAULT.providers[p][k]; renderEditor(); });')
        $writer.WriteLine('  root.querySelectorAll("button[data-delp]").forEach(b=>b.onclick=()=>{ delete VAULT.providers[b.dataset.delp]; renderEditor(); });')
        $writer.WriteLine('  root.querySelectorAll("button[data-addf]").forEach(b=>b.onclick=()=>{ const p=b.dataset.addf; const nf=root.querySelector(`.nf[data-np="${CSS.escape(p)}"]`).value.trim(); const nv=root.querySelector(`.nv[data-np="${CSS.escape(p)}"]`).value; if(nf){ VAULT.providers[p][nf]=nv; renderEditor(); } });')
        $writer.WriteLine('}')
        $writer.WriteLine('')
        $writer.WriteLine('document.getElementById("file").onchange=e=>{ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{ blob.value=r.result.trim(); }; r.readAsText(f); };')
        $writer.WriteLine('openBtn.onclick=async()=>{')
        $writer.WriteLine('  const m=document.getElementById("openMsg"); m.className="msg"; m.textContent="";')
        $writer.WriteLine('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }')
        $writer.WriteLine('  if(!blob.value.trim()){ m.className="msg err"; m.textContent=tr("noInput"); return; }')
        $writer.WriteLine('  try{ VAULT=await decryptB64(blob.value,pass.value); if(!VAULT.providers)VAULT.providers={}; renderEditor(); m.className="msg ok"; m.textContent=tr("opened"); }')
        $writer.WriteLine('  catch(err){ m.className="msg err"; m.textContent=tr("bad"); }')
        $writer.WriteLine('};')
        $writer.WriteLine('newBtn.onclick=()=>{')
        $writer.WriteLine('  const m=document.getElementById("openMsg");')
        $writer.WriteLine('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }')
        $writer.WriteLine('  VAULT={meta:{created:new Date().toISOString().slice(0,10),format:"SVPB1"},providers:{}}; renderEditor();')
        $writer.WriteLine('  m.className="msg ok"; m.textContent=tr("created");')
        $writer.WriteLine('};')
        $writer.WriteLine('addProvBtn.onclick=()=>{ if(!VAULT){ return; } const n=newProv.value.trim(); if(n){ VAULT.providers[n]=VAULT.providers[n]||{}; newProv.value=""; renderEditor(); } };')
        $writer.WriteLine('encBtn.onclick=async()=>{')
        $writer.WriteLine('  const m=document.getElementById("saveMsg"); m.className="msg";')
        $writer.WriteLine('  if(!VAULT){ m.className="msg err"; m.textContent=tr("needOpen"); return; }')
        $writer.WriteLine('  if(!pass.value){ m.className="msg err"; m.textContent=tr("needPass"); return; }')
        $writer.WriteLine('  result.value=await encryptObj(VAULT,pass.value); m.className="msg ok"; m.textContent=tr("encrypted");')
        $writer.WriteLine('};')
        $writer.WriteLine('dlBtn.onclick=()=>{ if(!result.value)return; try{ const b=new Blob([result.value],{type:"text/plain"}); const u=URL.createObjectURL(b); const a=document.createElement("a"); a.href=u; a.download="vault.svpb"; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){} };')
        $writer.WriteLine('expBtn.onclick=()=>{ if(!VAULT)return; result.value=JSON.stringify(VAULT,null,2); };')
        $writer.WriteLine('</script>')
        $writer.WriteLine('</body>')
        $writer.WriteLine('</html>')

        Write-Host "HTML file generated: $OutputFile"
    }
    finally {
        $writer.Close()
        $stream.Close()
    }
}

Main
