#!/usr/bin/env pwsh
# 3d.tcl — portiert nach powershell
# Quelle: tcl, Projects@abstractions:tcl/3d.tcl
# Erzeugt: 2026-08-19 durch ABSTRACTIONS_MANAGER.py

# 3d.html — portiert nach PowerShell 7
# Quelle: html, Projects@secret-vault-public:public/3d.html
# Erzeugt: 2026-08-09 durch ABSTRACTIONS_MANAGER.py

# PowerShell 7 script to generate 3d.html
# This script creates the HTML file programmatically, not as a string literal

function Write-HeadSection {
    param($StreamWriter)
    
    $StreamWriter.WriteLine("<head>")
    $StreamWriter.WriteLine("<meta charset=""utf-8"">")
    $StreamWriter.WriteLine("<meta name=""viewport"" content=""width=device-width, initial-scale=1"">")
    $StreamWriter.WriteLine("<title>Secret-Vault Public — Interaktive Architektur</title>")
    $StreamWriter.WriteLine("<meta name=""description"" content=""Vom Passwort zur verschlüsselten Datei — jede Schicht bleibt im Browser. Drehen, zoomen, Knoten auswählen."">")
    $StreamWriter.WriteLine("<meta name=""theme-color"" content=""#5b5bd6"">")
    
    # Write CSS styles
    Write-Styles -StreamWriter $StreamWriter
    
    $StreamWriter.WriteLine("</head>")
}

function Write-Styles {
    param($StreamWriter)
    
    $StreamWriter.WriteLine("<style>")
    $StreamWriter.WriteLine("  :root{")
    $StreamWriter.WriteLine("    --bg:#fbfaf7; --panel:#fff; --line:#e6e3dc; --text:#16191d; --muted:#5f6773;")
    $StreamWriter.WriteLine("    --ac:#5b5bd6; --buehne:#0e1420; --buehne-line:#1d2739;")
    $StreamWriter.WriteLine("    color-scheme: light;")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("  @media (prefers-color-scheme: dark){")
    $StreamWriter.WriteLine("    :root{ --bg:#0f1115; --panel:#171a21; --line:#262b36; --text:#f2f4f8; --muted:#9aa3b2;")
    $StreamWriter.WriteLine("           color-scheme: dark; }")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("  *{box-sizing:border-box}")
    $StreamWriter.WriteLine("  body{margin:0;background:var(--bg);color:var(--text);")
    $StreamWriter.WriteLine("       font:15px/1.55 -apple-system,BlinkMacSystemFont,""Segoe UI"",Roboto,sans-serif}")
    $StreamWriter.WriteLine("  .wrap{max-width:1240px;margin:0 auto;padding:34px 22px 60px}")
    $StreamWriter.WriteLine("  .technik{font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;")
    $StreamWriter.WriteLine("           color:var(--ac);margin:0 0 10px}")
    $StreamWriter.WriteLine("  h1{font-size:clamp(30px,5vw,52px);line-height:1.05;margin:0 0 14px;letter-spacing:-.03em}")
    $StreamWriter.WriteLine("  .lede{font-size:16.5px;color:var(--muted);max-width:62ch;margin:0 0 26px}")
    $StreamWriter.WriteLine("  .raster{display:grid;grid-template-columns:minmax(0,1fr) 288px;gap:18px;align-items:start}")
    $StreamWriter.WriteLine("  @media (max-width:880px){ .raster{grid-template-columns:1fr} }")
    $StreamWriter.WriteLine("  .buehne{position:relative;background:var(--buehne);border-radius:14px;overflow:hidden;")
    $StreamWriter.WriteLine("          min-height:520px;aspect-ratio:16/11}")
    $StreamWriter.WriteLine("  .buehne canvas{display:block;width:100%;height:100%}")
    $StreamWriter.WriteLine("  .knoepfe{position:absolute;top:14px;right:14px;display:flex;gap:8px;z-index:2}")
    $StreamWriter.WriteLine("  button{font:inherit;font-size:14px;font-weight:650;padding:9px 14px;border-radius:9px;")
    $StreamWriter.WriteLine("         border:1px solid var(--line);background:var(--panel);color:var(--text);cursor:pointer}")
    $StreamWriter.WriteLine("  button:hover{border-color:var(--ac)}")
    $StreamWriter.WriteLine("  button[aria-pressed=""true""]{background:var(--ac);border-color:var(--ac);color:#fff}")
    $StreamWriter.WriteLine("  .karte{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px}")
    $StreamWriter.WriteLine("  .karte h2{font-size:11px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;")
    $StreamWriter.WriteLine("            color:var(--muted);margin:0 0 12px}")
    $StreamWriter.WriteLine("  .karte h3{font-size:23px;margin:0 0 4px;letter-spacing:-.02em}")
    $StreamWriter.WriteLine("  .karte .sub{color:var(--muted);margin:0 0 18px;font-size:14.5px}")
    $StreamWriter.WriteLine("  .feld{border-top:1px solid var(--line);padding:12px 0 0;margin:0 0 12px}")
    $StreamWriter.WriteLine("  .feld dt{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;")
    $StreamWriter.WriteLine("           color:var(--muted);margin:0 0 3px}")
    $StreamWriter.WriteLine("  .feld dd{margin:0;font-weight:650}")
    $StreamWriter.WriteLine("  .blaettern{display:flex;gap:8px;margin-top:16px}")
    $StreamWriter.WriteLine("  .blaettern button{flex:1;text-align:center;line-height:1.25;padding:11px 8px}")
    $StreamWriter.WriteLine("  .legende{display:flex;gap:22px;flex-wrap:wrap;margin:16px 0 0;font-size:13.5px;color:var(--muted)}")
    $StreamWriter.WriteLine("  .legende span{display:inline-flex;align-items:center;gap:9px}")
    $StreamWriter.WriteLine("  .strich{width:30px;height:0;border-top-width:3px;border-top-style:solid;display:inline-block}")
    $StreamWriter.WriteLine("  .fuss{margin:14px 0 0;font-size:13px;color:var(--muted);max-width:80ch}")
    $StreamWriter.WriteLine("  .fehler{padding:40px;text-align:center;color:var(--muted)}")
    $StreamWriter.WriteLine("  a{color:var(--ac)}")
    $StreamWriter.WriteLine("</style>")
}

function Write-BodySection {
    param($StreamWriter)
    
    $StreamWriter.WriteLine("<body>")
    $StreamWriter.WriteLine("<div class=""wrap"">")
    
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  <p class=""technik"">three.js · r128</p>")
    $StreamWriter.WriteLine("  <h1>Secret-Vault Public</h1>")
    $StreamWriter.WriteLine("  <p class=""lede"">Vom Passwort zur verschlüsselten Datei — jede Schicht bleibt im Browser. Drehen, zoomen, Knoten auswählen.</p>")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  <div class=""raster"">")
    $StreamWriter.WriteLine("    <div class=""buehne"" id=""buehne"">")
    $StreamWriter.WriteLine("      <div class=""knoepfe"">")
    $StreamWriter.WriteLine("        <button id=""btn-plus"" title=""Näher"">+</button>")
    $StreamWriter.WriteLine("        <button id=""btn-minus"" title=""Weiter weg"">−</button>")
    $StreamWriter.WriteLine("        <button id=""btn-reset"">Zurücksetzen</button>")
    $StreamWriter.WriteLine("        <button id=""btn-iso"" aria-pressed=""true"" title=""Isometrisch oder perspektivisch"">Iso</button>")
    $StreamWriter.WriteLine("      </div>")
    $StreamWriter.WriteLine("    </div>")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("    <aside class=""karte"">")
    $StreamWriter.WriteLine("      <h2>Ausgewählter Knoten</h2>")
    $StreamWriter.WriteLine("      <h3 id=""k-name"">—</h3>")
    $StreamWriter.WriteLine("      <p class=""sub"" id=""k-sub"">Knoten anklicken oder durchblättern</p>")
    $StreamWriter.WriteLine("      <dl class=""feld""><dt>Schicht</dt><dd id=""k-schicht"">—</dd></dl>")
    $StreamWriter.WriteLine("      <dl class=""feld""><dt>ID</dt><dd id=""k-id"">—</dd></dl>")
    $StreamWriter.WriteLine("      <div class=""blaettern"">")
    $StreamWriter.WriteLine("        <button id=""btn-prev"">←<br>Vorheriger</button>")
    $StreamWriter.WriteLine("        <button id=""btn-next"">Nächster<br>→</button>")
    $StreamWriter.WriteLine("      </div>")
    $StreamWriter.WriteLine("    </aside>")
    $StreamWriter.WriteLine("  </div>")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  <div class=""legende"" id=""legende""></div>")
    $StreamWriter.WriteLine("  <p class=""fuss"">Schematische Dokumentationsansicht — Blockgrößen messen weder Datenmenge noch Leistung. Keine Telemetrie, keine Fernabfragen: Die Seite lädt einmalig three.js vom CDN und rechnet danach ausschließlich lokal.</p>")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("</div>")
    
    # Write script tags
    Write-Scripts -StreamWriter $StreamWriter
    
    $StreamWriter.WriteLine("</body>")
}

function Write-Scripts {
    param($StreamWriter)
    
    $StreamWriter.WriteLine("<script src=""https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js""></script>")
    $StreamWriter.WriteLine("<script>")
    $StreamWriter.WriteLine("(function(){")
    $StreamWriter.WriteLine("  ""use strict"";")
    $StreamWriter.WriteLine("  var SPEC = {""schichten"": [{""name"": ""Eingaben"", ""farbe"": ""#5f6773"", ""blocks"": [{""id"": ""passphrase"", ""name"": ""Passphrase"", ""untertitel"": ""nie gespeichert""}, {""id"": ""vault-datei"", ""name"": ""Vault-Datei"", ""untertitel"": ""Ciphertext""}, {""id"": ""neue-felder"", ""name"": ""neue Felder"", ""untertitel"": ""Formular""}]}, {""name"": ""Schluesselableitung"", ""farbe"": ""#2481cc"", ""blocks"": [{""id"": ""pbkdf2-210k"", ""name"": ""PBKDF2 210k"", ""untertitel"": ""Iterationen""}, {""id"": ""salt-16-b"", ""name"": ""Salt 16 B"", ""untertitel"": ""zufaellig""}, {""id"": ""sha-256"", ""name"": ""SHA-256"", ""untertitel"": ""HMAC""}]}, {""name"": ""Verschluesselung"", ""farbe"": ""#5b5bd6"", ""blocks"": [{""id"": ""aes-256-gcm"", ""name"": ""AES-256-GCM"", ""untertitel"": ""authentisiert""}, {""id"": ""iv-12-b"", ""name"": ""IV 12 B"", ""untertitel"": ""nie doppelt""}, {""id"": ""crypto-subtle"", ""name"": ""crypto.subtle"", ""untertitel"": ""WebCrypto""}]}, {""name"": ""Verwaltung"", ""farbe"": ""#b45309"", ""blocks"": [{""id"": ""anbieter"", ""name"": ""Anbieter"", ""untertitel"": ""Gruppen""}, {""id"": ""felder"", ""name"": ""Felder"", ""untertitel"": ""Schluessel/Wert""}, {""id"": ""rotation"", ""name"": ""Rotation"", ""untertitel"": ""neuer Wert""}]}, {""name"": ""Ausgabe"", ""farbe"": ""#22a06b"", ""blocks"": [{""id"": ""download"", ""name"": ""Download"", ""untertitel"": ""Blob-URL""}, {""id"": ""export"", ""name"": ""Export"", ""untertitel"": ""JSON""}, {""id"": ""zwischenablage"", ""name"": ""Zwischenablage"", ""untertitel"": ""nur auf Klick""}]}], ""kanten"": [{""von"": ""passphrase"", ""nach"": ""pbkdf2-210k"", ""art"": ""fluss""}, {""von"": ""vault-datei"", ""nach"": ""salt-16-b"", ""art"": ""fluss""}, {""von"": ""neue-felder"", ""nach"": ""sha-256"", ""art"": ""fluss""}, {""von"": ""pbkdf2-210k"", ""nach"": ""aes-256-gcm"", ""art"": ""fluss""}, {""von"": ""salt-16-b"", ""nach"": ""iv-12-b"", ""art"": ""fluss""}, {""von"": ""sha-256"", ""nach"": ""crypto-subtle"", ""art"": ""fluss""}, {""von"": ""aes-256-gcm"", ""nach"": ""anbieter"", ""art"": ""fluss""}, {""von"": ""iv-12-b"", ""nach"": ""felder"", ""art"": ""fluss""}, {""von"": ""crypto-subtle"", ""nach"": ""rotation"", ""art"": ""fluss""}, {""von"": ""anbieter"", ""nach"": ""download"", ""art"": ""fluss""}, {""von"": ""felder"", ""nach"": ""export"", ""art"": ""fluss""}, {""von"": ""rotation"", ""nach"": ""zwischenablage"", ""art"": ""fluss""}], ""kantenarten"": [{""art"": ""fluss"", ""farbe"": ""#5b5bd6"", ""stil"": ""voll"", ""text"": ""Fluss von unten nach oben""}]};")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  var buehne = document.getElementById(""buehne"");")
    $StreamWriter.WriteLine("  if (typeof THREE === ""undefined""){")
    $StreamWriter.WriteLine("    buehne.insertAdjacentHTML(""beforeend"",")
    $StreamWriter.WriteLine("      '<div class=""fehler"">three.js konnte nicht geladen werden. ' +")
    $StreamWriter.WriteLine("      'Die Seite braucht einmalig Netzzugang zum CDN.</div>');")
    $StreamWriter.WriteLine("    return;")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  // ---------------------------------------------------------------- Szene ---")
    $StreamWriter.WriteLine("  var szene = new THREE.Scene();")
    $StreamWriter.WriteLine("  szene.background = new THREE.Color(0x0e1420);")
    $StreamWriter.WriteLine("  var renderer = new THREE.WebGLRenderer({antialias:true});")
    $StreamWriter.WriteLine("  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));")
    $StreamWriter.WriteLine("  buehne.appendChild(renderer.domElement);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  var D = 26, radius = 82, aspekt = 1;")
    $StreamWriter.WriteLine("  var kameraIso = new THREE.OrthographicCamera(-D, D, D, -D, 0.1, 600);")
    $StreamWriter.WriteLine("  var kameraPersp = new THREE.PerspectiveCamera(42, 1, 0.1, 600);")
    $StreamWriter.WriteLine("  var kamera = kameraIso, iso = true;")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  szene.add(new THREE.AmbientLight(0xffffff, 0.66));")
    $StreamWriter.WriteLine("  var licht = new THREE.DirectionalLight(0xffffff, 0.8);")
    $StreamWriter.WriteLine("  licht.position.set(30, 46, 26); szene.add(licht);")
    $StreamWriter.WriteLine("  var gegen = new THREE.DirectionalLight(0x8ea2ff, 0.3);")
    $StreamWriter.WriteLine("  gegen.position.set(-32, 16, -28); szene.add(gegen);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  var raster = new THREE.GridHelper(110, 34, 0x25324a, 0x1a2333);")
    $StreamWriter.WriteLine("  raster.position.y = -24; szene.add(raster);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  // ------------------------------------------------------------ Schilder ---")
    $StreamWriter.WriteLine("  // Text auf eine Textur, dann als Billboard — bleibt bei jeder Drehung lesbar.")
    $StreamWriter.WriteLine("  function schild(text, unter){")
    $StreamWriter.WriteLine("    var c = document.createElement(""canvas""), x = c.getContext(""2d"");")
    $StreamWriter.WriteLine("    var f1 = ""700 40px -apple-system,Segoe UI,Roboto,sans-serif"";")
    $StreamWriter.WriteLine("    var f2 = ""500 27px -apple-system,Segoe UI,Roboto,sans-serif"";")
    $StreamWriter.WriteLine("    x.font = f1; var w1 = x.measureText(text).width;")
    $StreamWriter.WriteLine("    x.font = f2; var w2 = unter ? x.measureText(unter).width : 0;")
    $StreamWriter.WriteLine("    var w = Math.ceil(Math.max(w1, w2)) + 40, h = unter ? 96 : 62;")
    $StreamWriter.WriteLine("    c.width = w; c.height = h;")
    $StreamWriter.WriteLine("    x = c.getContext(""2d"");")
    $StreamWriter.WriteLine("    x.fillStyle = ""rgba(255,255,255,.95)"";")
    $StreamWriter.WriteLine("    if (x.roundRect){ x.beginPath(); x.roundRect(0,0,w,h,13); x.fill(); }")
    $StreamWriter.WriteLine("    else x.fillRect(0,0,w,h);")
    $StreamWriter.WriteLine("    x.fillStyle = ""#16191d""; x.font = f1; x.textBaseline = ""middle"";")
    $StreamWriter.WriteLine("    x.fillText(text, 20, unter ? 32 : 31);")
    $StreamWriter.WriteLine("    if (unter){ x.fillStyle = ""#5f6773""; x.font = f2; x.fillText(unter, 20, 68); }")
    $StreamWriter.WriteLine("    var t = new THREE.CanvasTexture(c); t.minFilter = THREE.LinearFilter;")
    $StreamWriter.WriteLine("    var s = new THREE.Sprite(new THREE.SpriteMaterial({map:t, transparent:true, depthTest:false}));")
    $StreamWriter.WriteLine("    s.scale.set(w/62*2.5, h/62*2.5, 1);")
    $StreamWriter.WriteLine("    s.renderOrder = 999;")
    $StreamWriter.WriteLine("    return s;")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  // -------------------------------------------------------------- Aufbau ---")
    $StreamWriter.WriteLine("  var BW = 7.4, BD = 4.2, BH = 1.7, LUFT = 1.3, ABSTAND = 11.4, START = -17;")
    $StreamWriter.WriteLine("  var knoten = [], nachId = {}, klickbar = [];")
    $StreamWriter.WriteLine("  var gruppe = new THREE.Group();")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  SPEC.schichten.forEach(function(sch, si){")
    $StreamWriter.WriteLine("    var y = START + si * ABSTAND;")
    $StreamWriter.WriteLine("    var bl = sch.blocks.map(function(b){")
    $StreamWriter.WriteLine("      return (typeof b === ""string"") ? {id:null, name:b, untertitel:""""} : b;")
    $StreamWriter.WriteLine("    });")
    $StreamWriter.WriteLine("    var spalten = Math.max(1, Math.ceil(bl.length / 2));")
    $StreamWriter.WriteLine("    var reihen = bl.length <= 1 ? 1 : 2;")
    $StreamWriter.WriteLine("    var gx = spalten*BW + (spalten-1)*LUFT, gz = reihen*BD + (reihen-1)*LUFT;")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("    var platte = new THREE.Mesh(")
    $StreamWriter.WriteLine("      new THREE.BoxGeometry(gx+3, 0.6, gz+3),")
    $StreamWriter.WriteLine("      new THREE.MeshLambertMaterial({color:new THREE.Color(sch.farbe).multiplyScalar(0.4)}));")
    $StreamWriter.WriteLine("    platte.position.set(0, y-1.7, 0); gruppe.add(platte);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("    bl.forEach(function(b, i){")
    $StreamWriter.WriteLine("      var sp = i % spalten, re = Math.floor(i / spalten);")
    $StreamWriter.WriteLine("      var x = -gx/2 + BW/2 + sp*(BW+LUFT), z = -gz/2 + BD/2 + re*(BD+LUFT);")
    $StreamWriter.WriteLine("      var mat = new THREE.MeshLambertMaterial({color:sch.farbe});")
    $StreamWriter.WriteLine("      var m = new THREE.Mesh(new THREE.BoxGeometry(BW, BH, BD), mat);")
    $StreamWriter.WriteLine("      m.position.set(x, y, z);")
    $StreamWriter.WriteLine("      gruppe.add(m); klickbar.push(m);")
    $StreamWriter.WriteLine("      var kante = new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),")
    $StreamWriter.WriteLine("        new THREE.LineBasicMaterial({color:0x0e1420, transparent:true, opacity:.55}));")
    $StreamWriter.WriteLine("      kante.position.copy(m.position); gruppe.add(kante);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("      var s = schild(b.name, b.untertitel);")
    $StreamWriter.WriteLine("      s.position.set(x, y + BH/2 + (b.untertitel ? 2.1 : 1.6), z);")
    $StreamWriter.WriteLine("      gruppe.add(s);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("      var id = b.id || (b.name.toLowerCase().replace(/[^a-z0-9]+/g, ""-"").replace(/^-|-\$/g, """"));")
    $StreamWriter.WriteLine("      var eintrag = {id:id, name:b.name, untertitel:b.untertitel||"""", schicht:sch.name,")
    $StreamWriter.WriteLine("                     mesh:m, mat:mat, farbe:new THREE.Color(sch.farbe), pos:m.position};")
    $StreamWriter.WriteLine("      m.userData.index = knoten.length;")
    $StreamWriter.WriteLine("      knoten.push(eintrag); nachId[id] = eintrag;")
    $StreamWriter.WriteLine("    });")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  // -------------------------------------------------------------- Kanten ---")
    $StreamWriter.WriteLine("  var STIL = {};")
    $StreamWriter.WriteLine("  (SPEC.kantenarten || []).forEach(function(a){ STIL[a.art] = a; });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  (SPEC.kanten || []).forEach(function(k){")
    $StreamWriter.WriteLine("    var a = nachId[k.von], b = nachId[k.nach];")
    $StreamWriter.WriteLine("    if (!a || !b) return;")
    $StreamWriter.WriteLine("    var art = STIL[k.art] || {farbe:""#8ea2ff"", stil:""voll""};")
    $StreamWriter.WriteLine("    var g = new THREE.BufferGeometry().setFromPoints([")
    $StreamWriter.WriteLine("      a.pos.clone().setY(a.pos.y + 0.9), b.pos.clone().setY(b.pos.y - 0.9)]);")
    $StreamWriter.WriteLine("    var linie;")
    $StreamWriter.WriteLine("    if (art.stil === ""gestrichelt""){")
    $StreamWriter.WriteLine("      linie = new THREE.Line(g, new THREE.LineDashedMaterial(")
    $StreamWriter.WriteLine("        {color:art.farbe, dashSize:1.4, gapSize:1.0, transparent:true, opacity:.9}));")
    $StreamWriter.WriteLine("      linie.computeLineDistances();")
    $StreamWriter.WriteLine("    } else {")
    $StreamWriter.WriteLine("      linie = new THREE.Line(g, new THREE.LineBasicMaterial(")
    $StreamWriter.WriteLine("        {color:art.farbe, transparent:true, opacity:.85}));")
    $StreamWriter.WriteLine("    }")
    $StreamWriter.WriteLine("    gruppe.add(linie);")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  szene.add(gruppe);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  var leg = document.getElementById(""legende"");")
    $StreamWriter.WriteLine("  (SPEC.kantenarten || []).forEach(function(a){")
    $StreamWriter.WriteLine("    var s = document.createElement(""span"");")
    $StreamWriter.WriteLine("    s.innerHTML = '<i class=""strich"" style=""border-top-color:' + a.farbe +")
    $StreamWriter.WriteLine("                  ';border-top-style:' + (a.stil === ""gestrichelt"" ? ""dashed"" : ""solid"") +")
    $StreamWriter.WriteLine("                  '""></i>' + a.text;")
    $StreamWriter.WriteLine("    leg.appendChild(s);")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  // ------------------------------------------------------------- Auswahl ---")
    $StreamWriter.WriteLine("  var aktiv = -1;")
    $StreamWriter.WriteLine("  function waehle(i){")
    $StreamWriter.WriteLine("    if (aktiv >= 0){")
    $StreamWriter.WriteLine("      knoten[aktiv].mat.color.copy(knoten[aktiv].farbe);")
    $StreamWriter.WriteLine("      knoten[aktiv].mat.emissive.setHex(0x000000);")
    $StreamWriter.WriteLine("      knoten[aktiv].mesh.scale.set(1,1,1);")
    $StreamWriter.WriteLine("    }")
    $StreamWriter.WriteLine("    aktiv = ((i % knoten.length) + knoten.length) % knoten.length;")
    $StreamWriter.WriteLine("    var k = knoten[aktiv];")
    $StreamWriter.WriteLine("    k.mat.emissive.setHex(0x333333);")
    $StreamWriter.WriteLine("    k.mesh.scale.set(1.1, 1.5, 1.1);")
    $StreamWriter.WriteLine("    document.getElementById(""k-name"").textContent = k.name;")
    $StreamWriter.WriteLine("    document.getElementById(""k-sub"").textContent = k.untertitel || ""—"";")
    $StreamWriter.WriteLine("    document.getElementById(""k-schicht"").textContent = k.schicht;")
    $StreamWriter.WriteLine("    document.getElementById(""k-id"").textContent = k.id;")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  var strahl = new THREE.Raycaster(), zeiger = new THREE.Vector2();")
    $StreamWriter.WriteLine("  renderer.domElement.addEventListener(""click"", function(e){")
    $StreamWriter.WriteLine("    if (gezogen) return;")
    $StreamWriter.WriteLine("    var r = renderer.domElement.getBoundingClientRect();")
    $StreamWriter.WriteLine("    zeiger.x = ((e.clientX - r.left) / r.width) * 2 - 1;")
    $StreamWriter.WriteLine("    zeiger.y = -((e.clientY - r.top) / r.height) * 2 + 1;")
    $StreamWriter.WriteLine("    strahl.setFromCamera(zeiger, kamera);")
    $StreamWriter.WriteLine("    var treffer = strahl.intersectObjects(klickbar, false);")
    $StreamWriter.WriteLine("    if (treffer.length) waehle(treffer[0].object.userData.index);")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("  document.getElementById(""btn-prev"").addEventListener(""click"", function(){ waehle(aktiv - 1); });")
    $StreamWriter.WriteLine("  document.getElementById(""btn-next"").addEventListener(""click"", function(){ waehle(aktiv + 1); });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  // ------------------------------------------------------------- Kamera ----")
    $StreamWriter.WriteLine("  var azimut = Math.PI/4, elevation = 0.62, rotiert = true;")
    $StreamWriter.WriteLine("  function stelle(){")
    $StreamWriter.WriteLine("    var x = radius*Math.cos(elevation)*Math.sin(azimut);")
    $StreamWriter.WriteLine("    var y = radius*Math.sin(elevation);")
    $StreamWriter.WriteLine("    var z = radius*Math.cos(elevation)*Math.cos(azimut);")
    $StreamWriter.WriteLine("    kamera.position.set(x, y, z); kamera.lookAt(0, 0, 0);")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("  var zieht = false, gezogen = false, lx = 0, ly = 0;")
    $StreamWriter.WriteLine("  renderer.domElement.addEventListener(""pointerdown"", function(e){")
    $StreamWriter.WriteLine("    zieht = true; gezogen = false; lx = e.clientX; ly = e.clientY;")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("  window.addEventListener(""pointermove"", function(e){")
    $StreamWriter.WriteLine("    if (!zieht) return;")
    $StreamWriter.WriteLine("    if (Math.abs(e.clientX-lx) + Math.abs(e.clientY-ly) > 3){ gezogen = true; rotiert = false; }")
    $StreamWriter.WriteLine("    azimut -= (e.clientX - lx) * 0.006;")
    $StreamWriter.WriteLine("    elevation = Math.max(0.08, Math.min(1.45, elevation + (e.clientY - ly) * 0.005));")
    $StreamWriter.WriteLine("    lx = e.clientX; ly = e.clientY;")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("  window.addEventListener(""pointerup"", function(){ zieht = false; setTimeout(function(){ gezogen = false; }, 0); });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  function zoom(f){")
    $StreamWriter.WriteLine("    if (iso){ D = Math.max(11, Math.min(54, D * f)); groesse(); }")
    $StreamWriter.WriteLine("    else { radius = Math.max(32, Math.min(160, radius * f)); }")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("  document.getElementById(""btn-plus"").addEventListener(""click"", function(){ zoom(0.85); });")
    $StreamWriter.WriteLine("  document.getElementById(""btn-minus"").addEventListener(""click"", function(){ zoom(1.18); });")
    $StreamWriter.WriteLine("  renderer.domElement.addEventListener(""wheel"", function(e){")
    $StreamWriter.WriteLine("    e.preventDefault(); zoom(e.deltaY > 0 ? 1.08 : 0.93);")
    $StreamWriter.WriteLine("  }, {passive:false});")
    $StreamWriter.WriteLine("  document.getElementById(""btn-reset"").addEventListener(""click"", function(){")
    $StreamWriter.WriteLine("    azimut = Math.PI/4; elevation = 0.62; D = 26; radius = 82; rotiert = true;")
    $StreamWriter.WriteLine("    iso = true; kamera = kameraIso;")
    $StreamWriter.WriteLine("    document.getElementById(""btn-iso"").setAttribute(""aria-pressed"", ""true"");")
    $StreamWriter.WriteLine("    document.getElementById(""btn-iso"").textContent = ""Iso"";")
    $StreamWriter.WriteLine("    waehle(0); groesse();")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("  document.getElementById(""btn-iso"").addEventListener(""click"", function(){")
    $StreamWriter.WriteLine("    iso = !iso; kamera = iso ? kameraIso : kameraPersp;")
    $StreamWriter.WriteLine("    this.setAttribute(""aria-pressed"", String(iso));")
    $StreamWriter.WriteLine("    this.textContent = iso ? ""Iso"" : ""Persp"";")
    $StreamWriter.WriteLine("    groesse();")
    $StreamWriter.WriteLine("  });")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  function groesse(){")
    $StreamWriter.WriteLine("    var w = buehne.clientWidth, h = buehne.clientHeight;")
    $StreamWriter.WriteLine("    aspekt = w / h;")
    $StreamWriter.WriteLine("    kameraIso.left = -D*aspekt; kameraIso.right = D*aspekt;")
    $StreamWriter.WriteLine("    kameraIso.top = D; kameraIso.bottom = -D; kameraIso.updateProjectionMatrix();")
    $StreamWriter.WriteLine("    kameraPersp.aspect = aspekt; kameraPersp.updateProjectionMatrix();")
    $StreamWriter.WriteLine("    renderer.setSize(w, h, false);")
    $StreamWriter.WriteLine("  }")
    $StreamWriter.WriteLine("  window.addEventListener(""resize"", groesse);")
    $StreamWriter.WriteLine("")
    $StreamWriter.WriteLine("  groesse();")
    $StreamWriter.WriteLine("  waehle(0);")
    $StreamWriter.WriteLine("  (function schleife(){")
    $StreamWriter.WriteLine("    requestAnimationFrame(schleife);")
    $StreamWriter.WriteLine("    if (rotiert) azimut += 0.003;")
    $StreamWriter.WriteLine("    stelle();")
    $StreamWriter.WriteLine("    renderer.render(szene, kamera);")
    $StreamWriter.WriteLine("  })();")
    $StreamWriter.WriteLine("})();")
    $StreamWriter.WriteLine("</script>")
}

function Generate-Html {
    param($Filename)
    
    $file = [System.IO.File]::CreateText($Filename)
    
    try {
        # Write DOCTYPE and html tag
        $file.WriteLine("<!DOCTYPE html>")
        $file.WriteLine("<html lang=""de"">")
        
        # Write head section
        Write-HeadSection -StreamWriter $file
        
        # Write body section
        Write-BodySection -StreamWriter $file
        
        # Close html tag
        $file.WriteLine("</html>")
    }
    finally {
        $file.Close()
    }
}

# Main execution
if ($args.Count -ne 1) {
    Write-Host "Usage: $($MyInvocation.MyCommand.Name) <output-file>"
    exit 1
}

$outputFile = $args[0]
Generate-Html -Filename $outputFile
Write-Host "Generated $outputFile"
