#!/usr/bin/env python3
"""
Database Maintainer Sub-Agent (Fixed)
Automated database maintenance with hourly checks, backups (3 days retention),
and tree command execution for important/openclaw-tree.txt.
"""

import os
import sqlite3
import hashlib
import json
import subprocess
from pathlib import Path
from datetime import datetime, timedelta
from shutil import copy2
import sys

# Use OPENCLAW_WORKSPACE env variable if set, otherwise default to /workspace
WORKSPACE = Path(os.getenv('OPENCLAW_WORKSPACE', '/workspace'))
DB_DIR = WORKSPACE / "db"
BACKUP_DIR = DB_DIR / "backups"
LOG_DIR = WORKSPACE / "logs" / "db-maintainer"
IMPORTANT_DIR = WORKSPACE / "important"

# Ensure directories exist (create if missing)
BACKUP_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)


class Logger:
    """Simple logger that writes to stdout and a daily log file."""
    def __init__(self):
        today = datetime.now().strftime('%Y-%m-%d')
        self.log_file = LOG_DIR / f"{today}.log"
    def log(self, level, message):
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        line = f"[{timestamp}] [{level}] {message}"
        print(line)
        with open(self.log_file, 'a', encoding='utf-8') as f:
            f.write(line + '\n')
    def info(self, msg): self.log('INFO', msg)
    def warn(self, msg): self.log('WARN', msg)
    def error(self, msg): self.log('ERROR', msg)


class DatabaseMaintainer:
    def __init__(self):
        self.logger = Logger()
        self.state_file = DB_DIR / "maintainer_state.json"
        self.retention_days = 3
    def load_state(self):
        if self.state_file.exists():
            with open(self.state_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        return {'last_check': None, 'last_backup': None, 'last_tree_update': None, 'file_hashes': {}}
    def save_state(self, state):
        with open(self.state_file, 'w', encoding='utf-8') as f:
            json.dump(state, f, indent=2)
    def get_file_hash(self, filepath):
        try:
            return hashlib.md5(filepath.read_bytes()).hexdigest()
        except Exception:
            return None
    def run_tree_command(self):
        """Execute 'tree -a -L 6' on the workspace. If the 'tree' binary is missing, fallback to 'find' for a similar listing."""
        try:
            result = subprocess.run(['tree', '-a', '-L', '6', str(WORKSPACE)], capture_output=True, text=True, timeout=60)
            if result.returncode == 0:
                self.logger.info("tree command succeeded")
                return result.stdout
            else:
                self.logger.warn(f"tree command failed (code {result.returncode}): {result.stderr.strip()}")
        except FileNotFoundError:
            self.logger.warn("tree binary not found, falling back to find")
        except Exception as e:
            self.logger.error(f"tree command exception: {e}")
        # Fallback using find to list up to depth 6
        try:
            find_result = subprocess.run(['find', str(WORKSPACE), '-maxdepth', '6', '-print'], capture_output=True, text=True, timeout=120)
            if find_result.returncode == 0:
                self.logger.info("fallback find command succeeded")
                return find_result.stdout
            else:
                self.logger.error(f"fallback find failed: {find_result.stderr.strip()}")
        except Exception as e:
            self.logger.error(f"fallback find exception: {e}")
        return None
    def update_tree_file(self, tree_output):
        if not tree_output:
            return False
        tree_file = IMPORTANT_DIR / "openclaw-tree.txt"
        header = f"# OpenClaw Workspace Tree\n# Generated: {datetime.now().isoformat()}\n# Command: tree -a -L 6 {WORKSPACE}\n# This file is auto‑generated by db‑maintainer\n\n"
        try:
            with open(tree_file, 'w', encoding='utf-8') as f:
                f.write(header)
                f.write(tree_output)
            self.logger.info(f"openclaw-tree.txt updated: {tree_file}")
            return True
        except Exception as e:
            self.logger.error(f"Failed to write openclaw-tree.txt: {e}")
            return False
    def scan_documentations(self):
        docs = []
        for pattern in ['*.md', '**/*.md']:
            for md_file in WORKSPACE.glob(pattern):
                if md_file.is_file() and not md_file.is_symlink():
                    if 'db/backups' in str(md_file) or 'node_modules' in str(md_file):
                        continue
                    docs.append({
                        'path': str(md_file.relative_to(WORKSPACE)),
                        'hash': self.get_file_hash(md_file),
                        'mtime': md_file.stat().st_mtime,
                    })
        return docs
    def check_for_changes(self):
        state = self.load_state()
        current_docs = self.scan_documentations()
        changes = []
        current_hashes = {}
        for doc in current_docs:
            path = doc['path']
            current_hashes[path] = doc['hash']
            if path not in state['file_hashes']:
                changes.append(f"NEW: {path}")
            elif state['file_hashes'][path] != doc['hash']:
                changes.append(f"CHANGED: {path}")
        for old_path in state['file_hashes']:
            if old_path not in current_hashes:
                changes.append(f"DELETED: {old_path}")
        return changes, current_hashes
    def update_databases(self):
        # Run the scripts that refresh docs.db and tree.db
        scripts = [WORKSPACE / 'scripts' / 'update_docs_db.py', WORKSPACE / 'scripts' / 'tree_indexer_v2.py']
        for script in scripts:
            try:
                result = subprocess.run(['python3', str(script)], capture_output=True, text=True, timeout=120)
                if result.returncode == 0:
                    self.logger.info(f"{script.name} succeeded")
                else:
                    self.logger.error(f"{script.name} failed: {result.stderr.strip()}")
                    return False
            except Exception as e:
                self.logger.error(f"Exception running {script.name}: {e}")
                return False
        return True
    def create_backup(self):
        timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M')
        for db_name in ['docs.db', 'tree.db']:
            source = DB_DIR / db_name
            if source.exists():
                backup_name = f"{timestamp}_{db_name}.bak"
                backup_path = BACKUP_DIR / backup_name
                copy2(source, backup_path)
                self.logger.info(f"Backup created: {backup_name}")
        return timestamp
    def cleanup_old_backups(self):
        cutoff = datetime.now() - timedelta(days=self.retention_days)
        deleted = 0
        for db_name in ['docs.db', 'tree.db']:
            for backup in BACKUP_DIR.glob(f"*_{db_name}.bak"):
                try:
                    date_part = backup.name.split('_')[0]
                    time_part = backup.name.split('_')[1]
                    backup_time = datetime.strptime(f"{date_part}_{time_part}", '%Y-%m-%d_%H-%M')
                    if backup_time < cutoff:
                        backup.unlink()
                        deleted += 1
                        self.logger.info(f"Deleted old backup: {backup.name}")
                except Exception:
                    self.logger.warn(f"Could not parse backup date: {backup.name}")
        if deleted == 0:
            self.logger.info("No old backups to delete")
        else:
            self.logger.info(f"Deleted {deleted} old backups (> {self.retention_days} days)")
    def run_cycle(self):
        self.logger.info("="*60)
        self.logger.info("DB Maintenance cycle start")
        self.logger.info("="*60)
        state = self.load_state()
        # Tree command and update file
        self.logger.info("Running tree command (depth 6)...")
        tree_output = self.run_tree_command()
        if tree_output:
            self.update_tree_file(tree_output)
            state['last_tree_update'] = datetime.now().isoformat()
        # DB updates
        self.logger.info("Updating docs.db and tree.db...")
        if self.update_databases():
            self.logger.info("Databases updated")
        # Check for docs changes and maybe trigger DB update (already done above)
        changes, current_hashes = self.check_for_changes()
        if changes:
            self.logger.info(f"Found {len(changes)} docs changes")
            for c in changes[:10]:
                self.logger